// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package orgmaintenancesettings

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"org_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [`/orgs`](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"wave_assignment_mode": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Mode configured for this organization that determines how maintenance waves are assigned to projects. Possible values are `MANUAL` and `ENV_TAG_MAPPING`. Defaults to `MANUAL` when unset. Only this field can be updated; Atlas derives read-only `effectiveWaveAssignmentMode` on GET responses and uses that value for scheduling when it differs from `waveAssignmentMode`. Omit this field to leave the current value unchanged. Specify null to reset to the default value (`MANUAL`).",
			},
		},
	}
}

type TFModel struct {
	OrgId              types.String `tfsdk:"org_id" autogen:"omitjson"`
	WaveAssignmentMode types.String `tfsdk:"wave_assignment_mode" autogen:"sendnullasnullonupdate"`
}
