// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package cloudbackupcollectionrestorejobcollection

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func PluralDataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"cluster_name": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human-readable label that identifies the cluster with the collection restore job you want to return.",
			},
			"job_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the collection restore job.",
			},
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.",
			},
			"results": dsschema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of returned documents that MongoDB Cloud provides when completing this request.",
				CustomType:          customtypes.NewNestedListType[TFPluralDSResultsModel](ctx),
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						"effective_target_namespace": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Actual target namespace after restore (e.g. after conflict rename).",
						},
						"index_status": dsschema.SingleNestedAttribute{
							Computed:            true,
							MarkdownDescription: "Index build status for a collection within a restore job.",
							CustomType:          customtypes.NewObjectType[TFPluralDSResultsIndexStatusModel](ctx),
							Attributes: map[string]dsschema.Attribute{
								"error_message": dsschema.StringAttribute{
									Computed:            true,
									MarkdownDescription: "Error message if index build failed.",
								},
								"failed_indexes": dsschema.ListAttribute{
									Computed:            true,
									MarkdownDescription: "List of index specifications that failed to build (up to 64 items).",
									CustomType:          customtypes.NewListType[jsontypes.Normalized](ctx),
									ElementType:         jsontypes.NormalizedType{},
								},
								"state": dsschema.StringAttribute{
									Computed:            true,
									MarkdownDescription: "Index build state indicating the status of index creation during or after a restore operation.",
								},
							},
						},
						"restored_documents": dsschema.Int64Attribute{
							Computed:            true,
							MarkdownDescription: "Number of documents restored so far.",
						},
						"source_namespace": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Source namespace that was requested to restore.",
						},
						"state": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Current state of this collection within the restore job.",
						},
						"target_namespace": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Requested target namespace for the restored collection.",
						},
						"total_documents": dsschema.Int64Attribute{
							Computed:            true,
							MarkdownDescription: "Total document count for this collection.",
						},
					},
				},
			},
			"source_namespace": dsschema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Source namespace to filter by (e.g. `db.collection`).",
			},
			"state": dsschema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Collection-level state to filter by.",
			},
			"target_namespace": dsschema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Target namespace to filter by (e.g. `db.collection`).",
			},
		},
	}
}

type TFPluralDSModel struct {
	ClusterName     types.String                                        `tfsdk:"cluster_name" autogen:"omitjson"`
	JobId           types.String                                        `tfsdk:"job_id" autogen:"omitjson"`
	ProjectId       types.String                                        `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Results         customtypes.NestedListValue[TFPluralDSResultsModel] `tfsdk:"results" autogen:"omitjson"`
	SourceNamespace types.String                                        `tfsdk:"source_namespace" autogen:"omitjson"`
	State           types.String                                        `tfsdk:"state" autogen:"omitjson"`
	TargetNamespace types.String                                        `tfsdk:"target_namespace" autogen:"omitjson"`
}
type TFPluralDSResultsModel struct {
	EffectiveTargetNamespace types.String                                               `tfsdk:"effective_target_namespace" autogen:"omitjson"`
	IndexStatus              customtypes.ObjectValue[TFPluralDSResultsIndexStatusModel] `tfsdk:"index_status" autogen:"omitjson"`
	RestoredDocuments        types.Int64                                                `tfsdk:"restored_documents" autogen:"omitjson"`
	SourceNamespace          types.String                                               `tfsdk:"source_namespace" autogen:"omitjson"`
	State                    types.String                                               `tfsdk:"state" autogen:"omitjson"`
	TargetNamespace          types.String                                               `tfsdk:"target_namespace" autogen:"omitjson"`
	TotalDocuments           types.Int64                                                `tfsdk:"total_documents" autogen:"omitjson"`
}
type TFPluralDSResultsIndexStatusModel struct {
	ErrorMessage  types.String                                `tfsdk:"error_message" autogen:"omitjson"`
	FailedIndexes customtypes.ListValue[jsontypes.Normalized] `tfsdk:"failed_indexes" autogen:"omitjson"`
	State         types.String                                `tfsdk:"state" autogen:"omitjson"`
}
