// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package federatedsettingsidentityproviderapi

import (
	"context"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/config"
)

var _ datasource.DataSource = &pluralDS{}
var _ datasource.DataSourceWithConfigure = &pluralDS{}

func PluralDataSource() datasource.DataSource {
	return &pluralDS{
		DSCommon: config.DSCommon{
			DataSourceName: "federated_settings_identity_provider_api_list",
		},
	}
}

type pluralDS struct {
	config.DSCommon
}

func (d *pluralDS) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = PluralDataSourceSchema(ctx)
}

func (d *pluralDS) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var tfConfig TFPluralDSModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &tfConfig)...)
	if resp.Diagnostics.HasError() {
		return
	}
	reqHandle := autogen.HandleDataSourceReadReq{
		Resp:       resp,
		Client:     d.Client,
		Config:     &tfConfig,
		CallParams: pluralDataSourceReadAPICallParams(&tfConfig),
	}
	autogen.HandleDataSourceReadList(ctx, reqHandle)
}

func pluralDataSourceReadAPICallParams(model *TFPluralDSModel) *config.APICallParams {
	pathParams := map[string]string{
		"federationSettingsId": model.FederationSettingsId.ValueString(),
	}
	queryParams := map[string]string{}
	if !model.IdpType.IsNull() && !model.IdpType.IsUnknown() {
		elements := make([]types.String, 0, len(model.IdpType.Elements()))
		diags := model.IdpType.ElementsAs(context.TODO(), &elements, false)
		if !diags.HasError() {
			var values []string
			for _, elem := range elements {
				if !elem.IsNull() && !elem.IsUnknown() {
					values = append(values, elem.ValueString())
				}
			}
			if len(values) > 0 {
				queryParams["idpType"] = strings.Join(values, ",")
			}
		}
	}
	if !model.Protocol.IsNull() && !model.Protocol.IsUnknown() {
		elements := make([]types.String, 0, len(model.Protocol.Elements()))
		diags := model.Protocol.ElementsAs(context.TODO(), &elements, false)
		if !diags.HasError() {
			var values []string
			for _, elem := range elements {
				if !elem.IsNull() && !elem.IsUnknown() {
					values = append(values, elem.ValueString())
				}
			}
			if len(values) > 0 {
				queryParams["protocol"] = strings.Join(values, ",")
			}
		}
	}
	return &config.APICallParams{
		VersionHeader: "application/vnd.atlas.2025-03-12+json",
		RelativePath:  "/api/atlas/v2/federationSettings/{federationSettingsId}/identityProviders",
		PathParams:    pathParams,
		QueryParams:   queryParams,
		Method:        "GET",
	}
}
