// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package federatedsettingsidentityproviderapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"acs_url": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "URL that points to where to send the SAML response.",
			},
			"associated_domains": schema.SetAttribute{
				Optional:            true,
				MarkdownDescription: "List that contains the domains associated with the identity provider.",
				CustomType:          customtypes.NewSetType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"associated_orgs": schema.SetNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List that contains the connected organization configurations associated with the identity provider.",
				CustomType:          customtypes.NewNestedSetType[TFAssociatedOrgsModel](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"data_access_identity_provider_ids": schema.SetAttribute{
							Computed:            true,
							MarkdownDescription: "The collection of unique ids representing the identity providers that can be used for data access in this organization.",
							CustomType:          customtypes.NewSetType[types.String](ctx),
							ElementType:         types.StringType,
						},
						"domain_allow_list": schema.SetAttribute{
							Computed:            true,
							MarkdownDescription: "Approved domains that restrict users who can join the organization based on their email address.",
							CustomType:          customtypes.NewSetType[types.String](ctx),
							ElementType:         types.StringType,
						},
						"domain_restriction_enabled": schema.BoolAttribute{
							Computed:            true,
							MarkdownDescription: "Value that indicates whether domain restriction is enabled for this connected org.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Legacy 20-hexadecimal digit string that identifies the UI access identity provider that this connected org config is associated with. This id can be found within the Federation Management Console > Identity Providers tab by clicking the info icon in the IdP ID row of a configured identity provider.",
						},
						"org_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the connected organization configuration.",
						},
						"post_auth_role_grants": schema.SetAttribute{
							Computed:            true,
							MarkdownDescription: "Atlas roles that are granted to a user in this organization after authenticating. Roles are a human-readable label that identifies the collection of privileges that MongoDB Cloud grants a specific MongoDB Cloud user. These roles can only be organization specific roles.",
							CustomType:          customtypes.NewSetType[types.String](ctx),
							ElementType:         types.StringType,
						},
						"role_mappings": schema.SetNestedAttribute{
							Computed:            true,
							MarkdownDescription: "Role mappings that are configured in this organization.",
							CustomType:          customtypes.NewNestedSetType[TFAssociatedOrgsRoleMappingsModel](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"external_group_name": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Unique human-readable label that identifies the identity provider group to which this role mapping applies.",
									},
									"id": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Unique 24-hexadecimal digit string that identifies this role mapping.",
									},
									"role_assignments": schema.SetNestedAttribute{
										Computed:            true,
										MarkdownDescription: "Atlas roles and the unique identifiers of the groups and organizations associated with each role. The array must include at least one element with an Organization role and its respective **orgId**. Each element in the array can have a value for **orgId** or **groupId**, but not both.",
										CustomType:          customtypes.NewNestedSetType[TFAssociatedOrgsRoleMappingsRoleAssignmentsModel](ctx),
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"group_id": schema.StringAttribute{
													Computed:            true,
													MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the project to which this role belongs. Each element within **roleAssignments** can have a value for **groupId** or **orgId**, but not both.",
												},
												"org_id": schema.StringAttribute{
													Computed:            true,
													MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization to which this role belongs. Each element within **roleAssignments** can have a value for **orgId** or **groupId**, but not both.",
												},
												"role": schema.StringAttribute{
													Computed:            true,
													MarkdownDescription: "Human-readable label that identifies the collection of privileges that MongoDB Cloud grants a specific API key, MongoDB Cloud user, or MongoDB Cloud team. These roles include organization- and project-level roles.",
												},
											},
										},
									},
								},
							},
						},
						"user_conflicts": schema.ListNestedAttribute{
							Computed:            true,
							MarkdownDescription: "List that contains the users who have an email address that doesn't match any domain on the allowed list.",
							CustomType:          customtypes.NewNestedListType[TFAssociatedOrgsUserConflictsModel](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"email_address": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Email address of the MongoDB Cloud user linked to the federated organization.",
									},
									"federation_settings_id": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the federation to which this MongoDB Cloud user belongs.",
									},
									"first_name": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "First or given name that belongs to the MongoDB Cloud user.",
									},
									"last_name": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Last name, family name, or surname that belongs to the MongoDB Cloud user.",
									},
									"user_id": schema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Unique 24-hexadecimal digit string that identifies this user.",
									},
								},
							},
						},
					},
				},
			},
			"audience": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Identifier of the intended recipient of the token.",
			},
			"audience_uri": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unique string that identifies the intended audience of the SAML assertion.",
			},
			"authorization_type": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Indicates whether authorization is granted based on group membership or user ID.",
			},
			"client_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Client identifier that is assigned to an application by the Identity Provider.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Date that the identity provider was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "The description of the identity provider.",
			},
			"display_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Human-readable label that identifies the identity provider.",
			},
			"federation_settings_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your federation.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"groups_claim": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Identifier of the claim which contains IdP Group IDs in the token.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the identity provider.",
			},
			"idp_type": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "String enum that indicates the type of the identity provider. Default is WORKFORCE.",
			},
			"issuer_uri": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Unique string that identifies the issuer of the SAML Assertion or OIDC metadata/discovery document URL.",
			},
			"okta_idp_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Legacy 20-hexadecimal digit string that identifies the identity provider.",
			},
			"pem_file_info": schema.SingleNestedAttribute{
				Optional:            true,
				MarkdownDescription: "PEM file information for the identity provider's current certificates.",
				CustomType:          customtypes.NewObjectType[TFPemFileInfoModel](ctx),
				Attributes: map[string]schema.Attribute{
					"certificates": schema.ListNestedAttribute{
						Optional:            true,
						MarkdownDescription: "List of certificates in the file.",
						CustomType:          customtypes.NewNestedListType[TFPemFileInfoCertificatesModel](ctx),
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"content": schema.StringAttribute{
									Optional:            true,
									MarkdownDescription: "Certificate content.",
								},
								"not_after": schema.StringAttribute{
									Optional:            true,
									MarkdownDescription: "Latest date that the certificate is valid. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
								},
								"not_before": schema.StringAttribute{
									Optional:            true,
									MarkdownDescription: "Earliest date that the certificate is valid. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
								},
							},
						},
					},
					"file_name": schema.StringAttribute{
						Optional:            true,
						MarkdownDescription: "Human-readable label given to the file.",
					},
				},
			},
			"protocol": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "String enum that indicates the protocol of the identity provider. Either SAML or OIDC.",
			},
			"request_binding": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "SAML Authentication Request Protocol HTTP method binding (POST or REDIRECT) that Federated Authentication uses to send the authentication request.",
			},
			"requested_scopes": schema.ListAttribute{
				Optional:            true,
				MarkdownDescription: "Scopes that MongoDB applications will request from the authorization endpoint.",
				CustomType:          customtypes.NewListType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"response_signature_algorithm": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Signature algorithm that Federated Authentication uses to encrypt the identity provider signature.",
			},
			"slug": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Custom SSO Url for the identity provider.",
			},
			"sso_debug_enabled": schema.BoolAttribute{
				Optional:            true,
				MarkdownDescription: "Flag that indicates whether the identity provider has SSO debug enabled.",
			},
			"sso_url": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "URL that points to the receiver of the SAML authentication request.",
			},
			"status": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "String enum that indicates whether the identity provider is active.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Date that the identity provider was last updated on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
			},
			"user_claim": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Identifier of the claim which contains the user ID in the token.",
			},
		},
	}
}

type TFModel struct {
	RequestedScopes            customtypes.ListValue[types.String]               `tfsdk:"requested_scopes"`
	AssociatedDomains          customtypes.SetValue[types.String]                `tfsdk:"associated_domains"`
	AssociatedOrgs             customtypes.NestedSetValue[TFAssociatedOrgsModel] `tfsdk:"associated_orgs" autogen:"omitjson"`
	Id                         types.String                                      `tfsdk:"id" autogen:"omitjson"`
	IssuerUri                  types.String                                      `tfsdk:"issuer_uri"`
	AuthorizationType          types.String                                      `tfsdk:"authorization_type"`
	ClientId                   types.String                                      `tfsdk:"client_id"`
	CreatedAt                  types.String                                      `tfsdk:"created_at" autogen:"omitjson"`
	Description                types.String                                      `tfsdk:"description"`
	DisplayName                types.String                                      `tfsdk:"display_name"`
	FederationSettingsId       types.String                                      `tfsdk:"federation_settings_id" autogen:"omitjson"`
	GroupsClaim                types.String                                      `tfsdk:"groups_claim"`
	AcsUrl                     types.String                                      `tfsdk:"acs_url" autogen:"omitjson"`
	IdpType                    types.String                                      `tfsdk:"idp_type"`
	AudienceUri                types.String                                      `tfsdk:"audience_uri" autogen:"omitjson"`
	OktaIdpId                  types.String                                      `tfsdk:"okta_idp_id" autogen:"omitjson"`
	PemFileInfo                customtypes.ObjectValue[TFPemFileInfoModel]       `tfsdk:"pem_file_info"`
	Protocol                   types.String                                      `tfsdk:"protocol"`
	RequestBinding             types.String                                      `tfsdk:"request_binding"`
	Audience                   types.String                                      `tfsdk:"audience"`
	ResponseSignatureAlgorithm types.String                                      `tfsdk:"response_signature_algorithm"`
	Slug                       types.String                                      `tfsdk:"slug"`
	UserClaim                  types.String                                      `tfsdk:"user_claim"`
	SsoUrl                     types.String                                      `tfsdk:"sso_url"`
	Status                     types.String                                      `tfsdk:"status"`
	UpdatedAt                  types.String                                      `tfsdk:"updated_at" autogen:"omitjson"`
	SsoDebugEnabled            types.Bool                                        `tfsdk:"sso_debug_enabled"`
}
type TFAssociatedOrgsModel struct {
	DataAccessIdentityProviderIds customtypes.SetValue[types.String]                              `tfsdk:"data_access_identity_provider_ids" autogen:"omitjson"`
	DomainAllowList               customtypes.SetValue[types.String]                              `tfsdk:"domain_allow_list" autogen:"omitjson"`
	PostAuthRoleGrants            customtypes.SetValue[types.String]                              `tfsdk:"post_auth_role_grants" autogen:"omitjson"`
	RoleMappings                  customtypes.NestedSetValue[TFAssociatedOrgsRoleMappingsModel]   `tfsdk:"role_mappings" autogen:"omitjson"`
	UserConflicts                 customtypes.NestedListValue[TFAssociatedOrgsUserConflictsModel] `tfsdk:"user_conflicts" autogen:"omitjson"`
	Id                            types.String                                                    `tfsdk:"id" apiname:"identityProviderId" autogen:"omitjson"`
	OrgId                         types.String                                                    `tfsdk:"org_id" autogen:"omitjson"`
	DomainRestrictionEnabled      types.Bool                                                      `tfsdk:"domain_restriction_enabled" autogen:"omitjson"`
}
type TFAssociatedOrgsRoleMappingsModel struct {
	ExternalGroupName types.String                                                                 `tfsdk:"external_group_name" autogen:"omitjson"`
	Id                types.String                                                                 `tfsdk:"id" autogen:"omitjson"`
	RoleAssignments   customtypes.NestedSetValue[TFAssociatedOrgsRoleMappingsRoleAssignmentsModel] `tfsdk:"role_assignments" autogen:"omitjson"`
}
type TFAssociatedOrgsRoleMappingsRoleAssignmentsModel struct {
	GroupId types.String `tfsdk:"group_id" autogen:"omitjson"`
	OrgId   types.String `tfsdk:"org_id" autogen:"omitjson"`
	Role    types.String `tfsdk:"role" autogen:"omitjson"`
}
type TFAssociatedOrgsUserConflictsModel struct {
	EmailAddress         types.String `tfsdk:"email_address" autogen:"omitjson"`
	FederationSettingsId types.String `tfsdk:"federation_settings_id" autogen:"omitjson"`
	FirstName            types.String `tfsdk:"first_name" autogen:"omitjson"`
	LastName             types.String `tfsdk:"last_name" autogen:"omitjson"`
	UserId               types.String `tfsdk:"user_id" autogen:"omitjson"`
}
type TFPemFileInfoModel struct {
	Certificates customtypes.NestedListValue[TFPemFileInfoCertificatesModel] `tfsdk:"certificates"`
	FileName     types.String                                                `tfsdk:"file_name"`
}
type TFPemFileInfoCertificatesModel struct {
	Content   types.String `tfsdk:"content"`
	NotAfter  types.String `tfsdk:"not_after"`
	NotBefore types.String `tfsdk:"not_before"`
}
