// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package mcpconfig

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func PluralDataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"org_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization that contains your projects.",
			},
			"results": dsschema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of returned documents that MongoDB Cloud provides when completing this request.",
				CustomType:          customtypes.NewNestedListType[TFPluralDSResultsModel](ctx),
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						"client_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique identifier for the Service Account client associated with this MCP configuration. Use this Service Account to connect to the Atlas Remote MCP.",
						},
						"egress_client_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique identifier for the egress Service Account client associated with this MCP configuration. This Service Account is managed by MongoDB Atlas.",
						},
						"ip_access_list": dsschema.SetNestedAttribute{
							Computed:            true,
							MarkdownDescription: "List of IP access list entries that define allowed source addresses for this MCP configuration.",
							CustomType:          customtypes.NewNestedSetType[TFPluralDSResultsIpAccessListModel](ctx),
							NestedObject: dsschema.NestedAttributeObject{
								Attributes: map[string]dsschema.Attribute{
									"cidr_block": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Range of network addresses in the access list for the Service Account. This parameter requires the range to be expressed in Classless Inter-Domain Routing (CIDR) notation of Internet Protocol version 4 or version 6 addresses. You can set a value for this parameter or `ipAddress`, but not for both in the same request.",
									},
									"created_at": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Date MongoDB Cloud added the entry was added to the Access List. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
									},
									"ip_address": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Network address in the access list for the Service Account. This parameter requires the address to be expressed as one Internet Protocol version 4 or version 6 address. You can set a value for this parameter or `cidrBlock`, but not for both in the same request.",
									},
									"last_used_address": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Network address that issued the most recent request to the API. This parameter requires the address to be expressed as one Internet Protocol version 4 or version 6 address. The resource returns this parameter after this IP address makes at least one request.",
									},
									"last_used_at": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Date when MongoDB Cloud received the most recent request that originated from this Internet Protocol version 4 or version 6 address. The resource returns this parameter when at least one request originates from this IP address. MongoDB Cloud updates this parameter each time a client accesses the permitted resource, with a delay of up to 5 minutes. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
									},
									"request_count": dsschema.Int64Attribute{
										Computed:            true,
										MarkdownDescription: "The number of requests that has originated from this network address.",
									},
								},
							},
						},
						"mcp_config_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique identifier that identifies this MCP configuration.",
						},
						"mcp_config_name": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable name that identifies this MCP configuration.",
						},
						"roles": dsschema.SetAttribute{
							Computed:            true,
							MarkdownDescription: "List of organization roles associated with this MCP configuration.",
							CustomType:          customtypes.NewSetType[types.String](ctx),
							ElementType:         types.StringType,
						},
					},
				},
			},
		},
	}
}

type TFPluralDSModel struct {
	OrgId   types.String                                        `tfsdk:"org_id" autogen:"omitjson"`
	Results customtypes.NestedListValue[TFPluralDSResultsModel] `tfsdk:"results" autogen:"omitjson"`
}
type TFPluralDSResultsModel struct {
	ClientId       types.String                                                   `tfsdk:"client_id" autogen:"omitjson"`
	EgressClientId types.String                                                   `tfsdk:"egress_client_id" autogen:"omitjson"`
	IpAccessList   customtypes.NestedSetValue[TFPluralDSResultsIpAccessListModel] `tfsdk:"ip_access_list" autogen:"omitjson"`
	McpConfigId    types.String                                                   `tfsdk:"mcp_config_id" autogen:"omitjson"`
	McpConfigName  types.String                                                   `tfsdk:"mcp_config_name" autogen:"omitjson"`
	Roles          customtypes.SetValue[types.String]                             `tfsdk:"roles" autogen:"omitjson"`
}
type TFPluralDSResultsIpAccessListModel struct {
	CidrBlock       types.String `tfsdk:"cidr_block" autogen:"omitjson"`
	CreatedAt       types.String `tfsdk:"created_at" autogen:"omitjson"`
	IpAddress       types.String `tfsdk:"ip_address" autogen:"omitjson"`
	LastUsedAddress types.String `tfsdk:"last_used_address" autogen:"omitjson"`
	LastUsedAt      types.String `tfsdk:"last_used_at" autogen:"omitjson"`
	RequestCount    types.Int64  `tfsdk:"request_count" autogen:"omitjson"`
}
