#!/usr/bin/env bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep '\.go$')

if [[ -n "${STAGED_GO_FILES}" ]]; then
    make verify files="${STAGED_GO_FILES}"
fi

STAGED_TF_FILES=$(git diff --cached --name-only | grep '\.tf$')
if [[ -n "${STAGED_TF_FILES}" ]]; then
    echo "Checking the format of Terraform files"
    make tflint
fi
