// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package controlplaneipaddressesapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/config"
)

var _ datasource.DataSource = &pluralDS{}
var _ datasource.DataSourceWithConfigure = &pluralDS{}

func PluralDataSource() datasource.DataSource {
	return &pluralDS{
		DSCommon: config.DSCommon{
			DataSourceName: "control_plane_ip_addressess_api",
		},
	}
}

type pluralDS struct {
	config.DSCommon
}

func (d *pluralDS) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = PluralDataSourceSchema(ctx)
}

func (d *pluralDS) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var tfConfig TFPluralDSModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &tfConfig)...)
	if resp.Diagnostics.HasError() {
		return
	}
	reqHandle := autogen.HandleDataSourceReadReq{
		Resp:       resp,
		Client:     d.Client,
		Config:     &tfConfig,
		CallParams: pluralDataSourceReadAPICallParams(ctx, &tfConfig),
	}
	autogen.HandleDataSourceReadList(ctx, reqHandle)
}

func pluralDataSourceReadAPICallParams(ctx context.Context, model *TFPluralDSModel) *config.APICallParams {
	pathParams := map[string]string{}
	return &config.APICallParams{
		VersionHeader: "application/vnd.atlas.2024-08-05+json",
		RelativePath:  "/api/atlas/v2/unauth/controlPlaneIPAddresses",
		PathParams:    pathParams,
		Method:        "GET",
	}
}
