version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    allow:
      - dependency-type: "all"
    groups:
      gomod:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
  - package-ecosystem: github-actions
    directory: "/.github/templates/run-script-and-commit"
    schedule:
      interval: weekly
      day: sunday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
