version: 1
appendOnly: true
labels:
  - label: "breaking-change"
    title: "!"
  - label: "enhancement"
    title: "feat:*"
  - label: "enhancement"
    title: "feature:*"
  - label: "bug"
    title: "fix:*"

