with-expecter: false
disable-version-string: true
dir: internal/testutil/mocksvc
outpkg: mocksvc
filename: "{{ .InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"

packages:
  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/searchdeployment:
    interfaces:
      DeploymentService:

  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/encryptionatrest:
    interfaces:
      EarService:
  
  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/project:
    interfaces:
      GroupProjectService:
  
  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/advancedcluster:
    interfaces:
      ClusterService:
