with-expecter: true
disable-version-string: true
dir: internal/testutil/mocksvc
outpkg: mocksvc
filename: "{{ .InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"

packages:
  go.mongodb.org/atlas-sdk/v20231115007/admin:
    interfaces:
      AtlasSearchApi:
      EncryptionAtRestUsingCustomerKeyManagementApi:

  
  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/project:
    interfaces:
      GroupProjectService:
  
  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/advancedcluster:
    interfaces:
      ClusterService:
