with-expecter: true
disable-version-string: true
dir: internal/testutil/mocksvc
outpkg: mocksvc
filename: "{{ .InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"

packages:
  go.mongodb.org/atlas-sdk/v20231115008/admin:
    interfaces:
      AtlasSearchApi:
      EncryptionAtRestUsingCustomerKeyManagementApi:
      TeamsApi:
      ProjectsApi:
      ClustersApi:
  
  github.com/mongodb/terraform-provider-mongodbatlas/internal/service/advancedcluster:
    interfaces:
      ClusterService:
