// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package cloudbackupcollectionrestorejob

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/conversion"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/config"
)

var _ resource.ResourceWithConfigure = &rs{}
var _ resource.ResourceWithImportState = &rs{}

const apiVersionHeader = "application/vnd.atlas.2025-03-12+json"

func Resource() resource.Resource {
	return &rs{
		RSCommon: config.RSCommon{
			ResourceName: "cloud_backup_collection_restore_job",
		},
	}
}

type rs struct {
	config.RSCommon
}

func (r *rs) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = ResourceSchema(ctx)
	if schemaHook, ok := any(r).(autogen.ResourceSchemaHook); ok {
		resp.Schema = schemaHook.ResourceSchema(ctx, resp.Schema)
	}
	conversion.UpdateSchemaDescription(&resp.Schema)
}

func (r *rs) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TFModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	pathParams := map[string]string{
		"projectId":   plan.ProjectId.ValueString(),
		"clusterName": plan.ClusterName.ValueString(),
	}
	callParams := config.APICallParams{
		VersionHeader: apiVersionHeader,
		RelativePath:  "/api/atlas/v2/groups/{projectId}/clusters/{clusterName}/collectionRestoreJobs",
		PathParams:    pathParams,
		Method:        "POST",
	}
	timeout, localDiags := plan.Timeouts.Create(ctx, 10800*time.Second)
	resp.Diagnostics.Append(localDiags...)
	if resp.Diagnostics.HasError() {
		return
	}
	reqHandle := autogen.HandleCreateReq{
		Hooks:      r,
		Resp:       resp,
		Client:     r.Client,
		Plan:       &plan,
		CallParams: &callParams,
		Wait: &autogen.WaitReq{
			StateProperty:     "state",
			PendingStates:     []string{"INITIALIZING", "IN_PROGRESS", "FINALIZING"},
			TargetStates:      []string{"SUCCESSFUL"},
			Timeout:           timeout,
			MinTimeoutSeconds: 60,
			DelaySeconds:      30,
			CallParams:        readAPICallParams,
		},
	}
	autogen.HandleCreate(ctx, reqHandle)
}

func (r *rs) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TFModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	reqHandle := autogen.HandleReadReq{
		Hooks:      r,
		RespDiags:  &resp.Diagnostics,
		RespState:  &resp.State,
		Client:     r.Client,
		State:      &state,
		CallParams: readAPICallParams(&state),
	}
	autogen.HandleRead(ctx, reqHandle)
}

func (r *rs) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Operation not supported", "This resource does not support updates. Delete and recreate the resource to apply changes.")
}

func (r *rs) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("Delete operation is a no-op", "This resource does not perform API calls during the delete operation. Terraform only removes the resource from state.")
}

func (r *rs) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idAttributes := []string{"project_id", "cluster_name", "job_id"}
	autogen.HandleImport(ctx, idAttributes, req, resp, r)
}

func readAPICallParams(model any) *config.APICallParams {
	m := model.(*TFModel)
	pathParams := map[string]string{
		"projectId":   m.ProjectId.ValueString(),
		"clusterName": m.ClusterName.ValueString(),
		"jobId":       m.JobId.ValueString(),
	}
	return &config.APICallParams{
		VersionHeader: apiVersionHeader,
		RelativePath:  "/api/atlas/v2/groups/{projectId}/clusters/{clusterName}/collectionRestoreJobs/{jobId}",
		PathParams:    pathParams,
		Method:        "GET",
	}
}
