package autogen

import (
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/config"
)

// CustomHooks aggregates all hook interfaces.
// Resource implementations typically satisfy this via embedding NoOpCustomCodeHooks and overriding only the hooks they care about.
type CustomHooks interface {
	CreateAPICallHooks
	ReadAPICallHooks
	UpdateAPICallHooks
	DeleteAPICallHooks
}

type CreateAPICallHooks interface {
	PreCreateAPICall(callParams config.APICallParams, bodyReq []byte) (config.APICallParams, []byte)
	PostCreateAPICall(APICallResult) APICallResult
}

type ReadAPICallHooks interface {
	PreReadAPICall(callParams config.APICallParams) config.APICallParams
	PostReadAPICall(HandleReadReq, APICallResult) APICallResult
}

type UpdateAPICallHooks interface {
	PreUpdateAPICall(callParams config.APICallParams, bodyReq []byte) (config.APICallParams, []byte)
	PostUpdateAPICall(APICallResult) APICallResult
}

type DeleteAPICallHooks interface {
	PreDeleteAPICall(callParams config.APICallParams) config.APICallParams
	PostDeleteAPICall(APICallResult) APICallResult
}

// NoOpCustomCodeHooks implements CustomHooks with no-op behavior, struct is embedded in the autogenerated resources.
var _ CustomHooks = &NoOpCustomCodeHooks{}

type NoOpCustomCodeHooks struct{}

func (h NoOpCustomCodeHooks) PreCreateAPICall(callParams config.APICallParams, bodyReq []byte) (updatedCallParams config.APICallParams, updatedBodyReq []byte) {
	return callParams, bodyReq
}

func (h NoOpCustomCodeHooks) PostCreateAPICall(result APICallResult) APICallResult {
	return result
}

func (h NoOpCustomCodeHooks) PreReadAPICall(callParams config.APICallParams) (updatedCallParams config.APICallParams) {
	return callParams
}

func (h NoOpCustomCodeHooks) PostReadAPICall(req HandleReadReq, result APICallResult) APICallResult {
	return result
}

func (h NoOpCustomCodeHooks) PreUpdateAPICall(callParams config.APICallParams, bodyReq []byte) (updatedCallParams config.APICallParams, updatedBodyReq []byte) {
	return callParams, bodyReq
}

func (h NoOpCustomCodeHooks) PostUpdateAPICall(result APICallResult) APICallResult {
	return result
}

func (h NoOpCustomCodeHooks) PreDeleteAPICall(callParams config.APICallParams) (updatedCallParams config.APICallParams) {
	return callParams
}

func (h NoOpCustomCodeHooks) PostDeleteAPICall(result APICallResult) APICallResult {
	return result
}
