// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package serviceaccountprojectassignment

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"client_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The Client ID of the Service Account.",
			},
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
			},
			"roles": dsschema.SetAttribute{
				Computed:            true,
				MarkdownDescription: "A list of Project roles associated with the Service Account.",
				CustomType:          customtypes.NewSetType[types.String](ctx),
				ElementType:         types.StringType,
			},
		},
	}
}

type TFDSModel struct {
	ClientId  types.String                       `tfsdk:"client_id" autogen:"omitjson"`
	ProjectId types.String                       `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Roles     customtypes.SetValue[types.String] `tfsdk:"roles" autogen:"omitjson"`
}
