// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package metricintegration

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"aggregation_temporality": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The temporality to send to the metric integration.",
			},
			"auth_type": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Authentication method the integration uses when exporting metrics to the endpoint.",
			},
			"endpoint": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "OpenTelemetry collector endpoint URL.",
			},
			"headers_redacted": dsschema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "HTTP headers for authentication and configuration. Values are redacted and never returned in plaintext.",
				CustomType:          customtypes.NewNestedListType[TFDSHeadersRedactedModel](ctx),
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						"name": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Header name.",
						},
						"value": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Redacted header value.",
						},
					},
				},
			},
			"integration_type": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Type of metric integration. Identifies which protocol will be used for the integration.",
			},
			"metric_integration_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique identifier of the metric integration configuration.",
			},
			"metric_selection": dsschema.SetAttribute{
				Computed:            true,
				MarkdownDescription: "Array of metric categories to export. Determines which types of metrics are sent to the integration.",
				CustomType:          customtypes.NewSetType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.",
			},
			"provider_type": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The provider type for the metric integration. Identifies the third-party service provider.",
			},
		},
	}
}

type TFDSModel struct {
	AggregationTemporality types.String                                          `tfsdk:"aggregation_temporality" autogen:"omitjson"`
	AuthType               types.String                                          `tfsdk:"auth_type" autogen:"omitjson"`
	Endpoint               types.String                                          `tfsdk:"endpoint" autogen:"omitjson"`
	HeadersRedacted        customtypes.NestedListValue[TFDSHeadersRedactedModel] `tfsdk:"headers_redacted" autogen:"emptyjsonaslist,omitjson"`
	IntegrationType        types.String                                          `tfsdk:"integration_type" autogen:"omitjson"`
	MetricIntegrationId    types.String                                          `tfsdk:"metric_integration_id" autogen:"omitjson"`
	MetricSelection        customtypes.SetValue[types.String]                    `tfsdk:"metric_selection" autogen:"emptyjsonaslist,omitjson"`
	ProjectId              types.String                                          `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	ProviderType           types.String                                          `tfsdk:"provider_type" autogen:"omitjson"`
}
type TFDSHeadersRedactedModel struct {
	Name  types.String `tfsdk:"name" autogen:"omitjson"`
	Value types.String `tfsdk:"value" autogen:"omitjson"`
}
