// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package metricintegration

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customvalidator"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"aggregation_temporality": schema.StringAttribute{ //
				Required:            true,
				MarkdownDescription: "The temporality to send to the metric integration.",
			},
			"endpoint": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.",
			},
			"group_id": schema.StringAttribute{ //
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.\n\n**NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"headers": schema.ListNestedAttribute{
				Optional:            true,
				MarkdownDescription: "HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.",
				CustomType:          customtypes.NewNestedListType[TFHeadersModel](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Required:            true,
							MarkdownDescription: "Header name.",
						},
						"value": schema.StringAttribute{
							Required:            true,
							MarkdownDescription: "Header value.",
							Sensitive:           true,
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Required:            true,	// id is listed as required in MetricIntegrationUpdateRequest (API spec), this should be computed-only
				MarkdownDescription: "Unique 24-character hexadecimal digit string that identifies the metric integration configuration.",
			},
			"integration_type": schema.StringAttribute{ //
				Required:            true,
				MarkdownDescription: "Type of metric integration. Identifies which protocol will be used for the integration. This value cannot be modified after the integration is created.",
				Validators: []validator.String{
					customvalidator.ValidateDiscriminator(customvalidator.DiscriminatorDefinition{
						Mapping: map[string]customvalidator.VariantDefinition{
							"OTEL": {
								Allowed:  []string{"endpoint", "headers"},
								Required: []string{"endpoint", "headers"},
							},
						},
					}),
				},
			},
			"metric_selection": schema.SetAttribute{ //
				Required:            true,
				MarkdownDescription: "Array of metric categories to export. Determines which types of metrics are sent to the integration.",
				CustomType:          customtypes.NewSetType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"provider_type": schema.StringAttribute{ //
				Required:            true,
				MarkdownDescription: "The provider type for the metric integration. Identifies the third-party service provider.",
			},
		},
	}
}

type TFModel struct {
	AggregationTemporality types.String                                `tfsdk:"aggregation_temporality"`
	Endpoint               types.String                                `tfsdk:"endpoint"`
	GroupId                types.String                                `tfsdk:"group_id" autogen:"omitjson"`
	Headers                customtypes.NestedListValue[TFHeadersModel] `tfsdk:"headers"`
	Id                     types.String                                `tfsdk:"id"`
	IntegrationType        types.String                                `tfsdk:"integration_type"`
	MetricSelection        customtypes.SetValue[types.String]          `tfsdk:"metric_selection"`
	ProviderType           types.String                                `tfsdk:"provider_type"`
}
type TFHeadersModel struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value" autogen:"sensitive"`
}
