// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package orgdelegationsettings

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"delegated_mcp_access": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Policy that controls how MCP (Model Context Protocol) delegated access is permitted within this organization. Possible values are `DISALLOWED`, `READ_ONLY`, and `READ_WRITE`. Defaults to `DISALLOWED`.",
			},
			"delegated_partner_access": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Policy that controls whether partner delegated access is permitted within this organization. Possible values are `DISALLOWED` and `READ_WRITE`. Defaults to `DISALLOWED`.",
			},
			"idle_refresh_token_lifetime": dsschema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Maximum number of seconds a refresh token may be idle before it expires. When not set, the system default applies.",
			},
			"maximum_refresh_token_lifetime": dsschema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Maximum lifetime of a refresh token in seconds, regardless of activity. When not set, the system default applies.",
			},
			"org_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization that contains your projects.",
			},
		},
	}
}

type TFDSModel struct {
	DelegatedMcpAccess          types.String `tfsdk:"delegated_mcp_access" autogen:"omitjson"`
	DelegatedPartnerAccess      types.String `tfsdk:"delegated_partner_access" autogen:"omitjson"`
	IdleRefreshTokenLifetime    types.Int64  `tfsdk:"idle_refresh_token_lifetime" autogen:"omitjson"`
	MaximumRefreshTokenLifetime types.Int64  `tfsdk:"maximum_refresh_token_lifetime" autogen:"omitjson"`
	OrgId                       types.String `tfsdk:"org_id" autogen:"omitjson"`
}
