// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package serviceaccount

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func PluralDataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"org_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization that contains your projects. Use the [/orgs](#tag/Organizations/operation/listOrganizations) endpoint to retrieve all organizations to which the authenticated user has access.",
			},
			"results": dsschema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of returned documents that MongoDB Cloud provides when completing this request.",
				CustomType:          customtypes.NewNestedListType[TFPluralDSResultsModel](ctx),
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						"client_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The Client ID of the Service Account.",
						},
						"created_at": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The date that the Service Account was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
						},
						"description": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human readable description for the Service Account.",
						},
						"name": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable name for the Service Account.",
						},
						"roles": dsschema.SetAttribute{
							Computed:            true,
							MarkdownDescription: "A list of Organization roles associated with the Service Account.",
							CustomType:          customtypes.NewSetType[types.String](ctx),
							ElementType:         types.StringType,
						},
						"secrets": dsschema.ListNestedAttribute{
							Computed:            true,
							MarkdownDescription: "A list of secrets associated with the specified Service Account.",
							CustomType:          customtypes.NewNestedListType[TFPluralDSResultsSecretsModel](ctx),
							NestedObject: dsschema.NestedAttributeObject{
								Attributes: map[string]dsschema.Attribute{
									"created_at": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "The date that the secret was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
									},
									"expires_at": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "The date for the expiration of the secret. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
									},
									"id": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the secret.",
									},
									"last_used_at": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "The last time the secret was used. This parameter expresses its value in the ISO 8601 timestamp format in UTC.",
									},
									"masked_secret_value": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "The masked Service Account secret.",
									},
									"secret": dsschema.StringAttribute{
										Computed:            true,
										MarkdownDescription: "The secret for the Service Account. It will be returned only the first time after creation.",
										Sensitive:           true,
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

type TFPluralDSModel struct {
	OrgId   types.String                                        `tfsdk:"org_id" autogen:"omitjson"`
	Results customtypes.NestedListValue[TFPluralDSResultsModel] `tfsdk:"results" autogen:"omitjson"`
}
type TFPluralDSResultsModel struct {
	ClientId    types.String                                               `tfsdk:"client_id" autogen:"omitjson"`
	CreatedAt   types.String                                               `tfsdk:"created_at" autogen:"omitjson"`
	Description types.String                                               `tfsdk:"description" autogen:"omitjson"`
	Name        types.String                                               `tfsdk:"name" autogen:"omitjson"`
	Roles       customtypes.SetValue[types.String]                         `tfsdk:"roles" autogen:"omitjson"`
	Secrets     customtypes.NestedListValue[TFPluralDSResultsSecretsModel] `tfsdk:"secrets" autogen:"omitjson"`
}
type TFPluralDSResultsSecretsModel struct {
	CreatedAt         types.String `tfsdk:"created_at" autogen:"omitjson"`
	ExpiresAt         types.String `tfsdk:"expires_at" autogen:"omitjson"`
	Id                types.String `tfsdk:"id" autogen:"omitjson"`
	LastUsedAt        types.String `tfsdk:"last_used_at" autogen:"omitjson"`
	MaskedSecretValue types.String `tfsdk:"masked_secret_value" autogen:"omitjson"`
	Secret            types.String `tfsdk:"secret" autogen:"sensitive,omitjson"`
}
