// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package privatelinkendpointservicedatafederationonlinearchive

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"comment": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Human-readable string to associate with this private endpoint.",
			},
			"customer_endpoint_dns_name": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Human-readable DNS name to identify the customer's endpoint. If defined, you must also specify a value for `region`.",
			},
			"endpoint_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 22-character alphanumeric string that identifies the private endpoint.",
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"provider_name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human-readable label that identifies the cloud service provider. Atlas Data Lake supports Amazon Web Services only.",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Human-readable region label for the customer's endpoint. If defined, you must also specify a value for `customer_endpoint_dns_name`.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Human-readable label that identifies the resource type associated with this private endpoint.",
			},
			"delete_on_create_timeout": schema.BoolAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Indicates whether to delete the resource being created if a timeout is reached when waiting for completion. When set to `true` and timeout occurs, it triggers the deletion and returns immediately without waiting for deletion to complete. When set to `false`, the timeout will not trigger resource deletion. If you suspect a transient error when the value is `true`, wait before retrying to allow resource deletion to finish. Default is `true`.",
				PlanModifiers:       []planmodifier.Bool{customplanmodifier.CreateOnlyBoolWithDefault(true)},
			},
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

type TFModel struct {
	TFExpandedModel
	Comment                 types.String   `tfsdk:"comment"`
	CustomerEndpointDNSName types.String   `tfsdk:"customer_endpoint_dns_name"`
	EndpointId              types.String   `tfsdk:"endpoint_id"`
	ProjectId               types.String   `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	ProviderName            types.String   `tfsdk:"provider_name" apiname:"provider"`
	Region                  types.String   `tfsdk:"region"`
	Type                    types.String   `tfsdk:"type"`
	DeleteOnCreateTimeout   types.Bool     `tfsdk:"delete_on_create_timeout" autogen:"omitjson"`
	Timeouts                timeouts.Value `tfsdk:"timeouts" autogen:"omitjson"`
}
