// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package clusteradaptivesettings

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"adaptive_settings_overrides": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "JSON-encoded map of customer-specified Adaptive Settings overrides, applied on a best-effort basis. Use `jsonencode` to configure this attribute. Each supported entry that you specify takes precedence over the corresponding Atlas-managed default.",
				CustomType:          jsontypes.NormalizedType{},
			},
			"cluster_name": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human-readable label that identifies the cluster.",
			},
			"effective_adaptive_settings": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "JSON-encoded map of the effective Adaptive Settings currently applied to your cluster, based on your overrides and Atlas-managed defaults. Atlas-managed defaults can vary by MongoDB version. An override for a setting unsupported by the cluster's MongoDB version doesn't take effect, and the effective value reflects the Atlas-managed default.",
				CustomType:          jsontypes.NormalizedType{},
			},
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.",
			},
		},
	}
}

type TFDSModel struct {
	AdaptiveSettingsOverrides jsontypes.Normalized `tfsdk:"adaptive_settings_overrides" autogen:"omitjson"`
	ClusterName               types.String         `tfsdk:"cluster_name" autogen:"omitjson"`
	EffectiveAdaptiveSettings jsontypes.Normalized `tfsdk:"effective_adaptive_settings" autogen:"omitjson"`
	ProjectId                 types.String         `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
}
