// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package privatelinkendpointservicedatafederationonlinearchiveapi

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func PluralDataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
			},
			"results": dsschema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of returned documents that MongoDB Cloud provides when completing this request.",
				CustomType:          customtypes.NewNestedListType[TFPluralDSResultsModel](ctx),
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						"azure_link_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Link ID that identifies the Azure private endpoint connection.",
						},
						"comment": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable string to associate with this private endpoint.",
						},
						"customer_endpoint_dns_name": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable DNS name to identify the customer's endpoint. If defined, you must also specify a value for `region`.",
						},
						"customer_endpoint_ip_address": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "IP address used to connect to the Azure private endpoint.",
						},
						"endpoint_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique 22-character alphanumeric string that identifies the private endpoint.",
						},
						"error_message": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Error message describing a failure approving the private endpoint request.",
						},
						"provider_name": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable label that identifies the cloud service provider. Atlas Data Lake supports Amazon Web Services only.",
						},
						"region": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable region label for the customer's endpoint. If defined, you must also specify a value for `customer_endpoint_dns_name`.",
						},
						"status": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Status of the private endpoint connection request.",
						},
						"type": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Human-readable label that identifies the resource type associated with this private endpoint.",
						},
					},
				},
			},
		},
	}
}

type TFPluralDSModel struct {
	TFPluralDSExpandedModel
	ProjectId types.String                                        `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Results   customtypes.NestedListValue[TFPluralDSResultsModel] `tfsdk:"results" autogen:"omitjson"`
}
type TFPluralDSResultsModel struct {
	AzureLinkId               types.String `tfsdk:"azure_link_id" autogen:"omitjson"`
	Comment                   types.String `tfsdk:"comment" autogen:"omitjson"`
	CustomerEndpointDNSName   types.String `tfsdk:"customer_endpoint_dns_name" autogen:"omitjson"`
	CustomerEndpointIPAddress types.String `tfsdk:"customer_endpoint_ip_address" autogen:"omitjson"`
	EndpointId                types.String `tfsdk:"endpoint_id" autogen:"omitjson"`
	ErrorMessage              types.String `tfsdk:"error_message" autogen:"omitjson"`
	ProviderName              types.String `tfsdk:"provider_name" apiname:"provider" autogen:"omitjson"`
	Region                    types.String `tfsdk:"region" autogen:"omitjson"`
	Status                    types.String `tfsdk:"status" autogen:"omitjson"`
	Type                      types.String `tfsdk:"type" autogen:"omitjson"`
}
