// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package privatelinkendpointservicedatafederationonlinearchiveapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"azure_link_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Link ID that identifies the Azure private endpoint connection.",
			},
			"comment": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Human-readable string to associate with this private endpoint.",
			},
			"customer_endpoint_dns_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Human-readable label to identify customer's VPC endpoint DNS name. If defined, you must also specify a value for **region**.",
			},
			"customer_endpoint_ip_address": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "IP address used to connect to the Azure private endpoint.",
			},
			"endpoint_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 22-character alphanumeric string that identifies the private endpoint.",
			},
			"error_message": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Error message describing a failure approving the private endpoint request.",
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.\n\n**NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"provider_name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human-readable label that identifies the cloud service provider. Atlas Data Lake supports Amazon Web Services only.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Human-readable label to identify the region of customer's VPC endpoint. If defined, you must also specify a value for **customerEndpointDNSName**.",
			},
			"status": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Status of the private endpoint connection request.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Human-readable label that identifies the resource type associated with this private endpoint.",
			},
		},
	}
}

type TFModel struct {
	AzureLinkId               types.String `tfsdk:"azure_link_id"`
	Comment                   types.String `tfsdk:"comment"`
	CustomerEndpointDNSName   types.String `tfsdk:"customer_endpoint_dns_name"`
	CustomerEndpointIPAddress types.String `tfsdk:"customer_endpoint_ip_address"`
	EndpointId                types.String `tfsdk:"endpoint_id"`
	ErrorMessage              types.String `tfsdk:"error_message"`
	ProjectId                 types.String `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Provider_name             types.String `tfsdk:"provider_name" apiname:"provider"`
	Region                    types.String `tfsdk:"region"`
	Status                    types.String `tfsdk:"status"`
	Type                      types.String `tfsdk:"type"`
}
