// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package aimodelorgapikey

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func PluralDataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"org_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the organization that contains your projects.",
			},
			"results": dsschema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of returned documents that MongoDB Cloud provides when completing this request.",
				CustomType:          customtypes.NewNestedListType[TFPluralDSResultsModel](ctx),
				NestedObject: dsschema.NestedAttributeObject{
					Attributes: map[string]dsschema.Attribute{
						"api_key_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Identifier used to reference this API key in admin API calls.",
						},
						"created_at": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "UTC date when the API key was created. This parameter is formatted as an ISO 8601 timestamp.",
						},
						"created_by": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Name of the user that created this API key. If no user name is available, the user ID is returned.",
						},
						"project_id": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
						},
						"last_used_at": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "UTC date when the API key was last used. This parameter is formatted as an ISO 8601 timestamp.",
						},
						"masked_secret": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "A partially obfuscated version of the API key secret returned when the API key was created.",
						},
						"name": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Arbitrary string identifier assigned to this API key for convenient identification.",
						},
						"status": dsschema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "A string describing the current status of the API key.",
						},
					},
				},
			},
		},
	}
}

type TFPluralDSModel struct {
	OrgId   types.String                                        `tfsdk:"org_id" autogen:"omitjson"`
	Results customtypes.NestedListValue[TFPluralDSResultsModel] `tfsdk:"results" autogen:"omitjson"`
}
type TFPluralDSResultsModel struct {
	ApiKeyId     types.String `tfsdk:"api_key_id" autogen:"omitjson"`
	CreatedAt    types.String `tfsdk:"created_at" autogen:"omitjson"`
	CreatedBy    types.String `tfsdk:"created_by" autogen:"omitjson"`
	Project_id   types.String `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	LastUsedAt   types.String `tfsdk:"last_used_at" autogen:"omitjson"`
	MaskedSecret types.String `tfsdk:"masked_secret" autogen:"omitjson"`
	Name         types.String `tfsdk:"name" autogen:"omitjson"`
	Status       types.String `tfsdk:"status" autogen:"omitjson"`
}
