resource "mongodbatlas_mcp_config" "this" {
  org_id          = var.org_id
  mcp_config_name = "example-mcp-config"
  roles           = ["ORG_READ_ONLY"]

  ip_access_list = [
    {
      cidr_block = "203.0.113.0/24"
    }
  ]
}

output "mcp_config_id" {
  value = mongodbatlas_mcp_config.this.mcp_config_id
}

output "client_id" {
  description = "Ingress Service Account client ID, used by the AI client to authenticate to the Remote MCP Server."
  value       = mongodbatlas_mcp_config.this.client_id
}

output "egress_client_id" {
  description = "Egress Service Account client ID, used for audit and compliance purposes. Audit log entries generated by MCP tool calls reference this ID."
  value       = mongodbatlas_mcp_config.this.egress_client_id
}
