// This tool identifies the Terraform documentation files that correspond to
// autogenerated (serviceapi) resources, based on tools/codegen/config.yml.
// Its output is used to decide when the Docs team should be notified and asked
// for review: autogenerated docs are excluded, as feedback for them belongs to
// the backend side (see tools/codegen).
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mongodb/terraform-provider-mongodbatlas/tools/codegen/config"
)

const (
	configPath     = "tools/codegen/config.yml"
	codeownersPath = ".github/CODEOWNERS"
	docsOwner      = "@mongodb/APIx-Integrations"
	beginMarker    = "# BEGIN autogenerated docs ownership (generated by `go run ./tools/autogendocslist -codeowners`, do not edit)"
	endMarker      = "# END autogenerated docs ownership"
)

// genericAPIGlobs cover docs for autogenerated resources whose name ends with
// _api. They are generated through the generic tfplugindocs template and moved
// by scripts/generate-docs-all.sh based on this naming convention.
var genericAPIGlobs = []string{
	"docs/resources/*_api.md",
	"docs/resources/*_api_v*.md",
	"docs/data-sources/*_api.md",
	"docs/data-sources/*_api_v*.md",
	"docs/ephemeral-resources/*_api.md",
	"docs/ephemeral-resources/*_api_v*.md",
}

func main() {
	root := flag.String("root", ".", "repository root directory")
	filtersOut := flag.String("filters", "", "write dorny/paths-filter YAML to this file")
	codeownersBlock := flag.Bool("codeowners", false, "print the CODEOWNERS block to stdout")
	check := flag.Bool("check", false, "verify the CODEOWNERS block in .github/CODEOWNERS matches the generated one")
	flag.Parse()

	docsPaths, err := autogenDocsPaths(*root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	switch {
	case *filtersOut != "":
		if err := writeFilters(*filtersOut, docsPaths); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	case *codeownersBlock:
		fmt.Print(codeownersBlockText(docsPaths))
	case *check:
		if err := checkCodeowners(*root); err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
	default:
		for _, p := range docsPaths {
			fmt.Println(p)
		}
	}
}

// autogenDocsPaths returns the documentation files (existing under root) that
// belong to autogenerated resources defined in tools/codegen/config.yml.
func autogenDocsPaths(root string) ([]string, error) {
	cfg, err := config.ParseGenConfigYAML(filepath.Join(root, configPath))
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", configPath, err)
	}

	var result []string
	for name := range cfg.Resources {
		if strings.HasSuffix(name, "_api") {
			// Covered by genericAPIGlobs.
			continue
		}
		candidates := []string{filepath.Join("docs", "resources", name+".md")}
		if ds := cfg.Resources[name].DataSources; ds != nil {
			if ds.Read != nil {
				candidates = append(candidates, filepath.Join("docs", "data-sources", name+".md"))
			}
			if ds.List != nil {
				candidates = append(candidates, filepath.Join("docs", "data-sources", name+"s.md"))
			}
		}
		for _, candidate := range candidates {
			if _, err := os.Stat(filepath.Join(root, candidate)); err == nil {
				result = append(result, candidate)
			}
		}
	}
	sort.Strings(result)
	return result, nil
}

func negated(paths []string) []string {
	result := make([]string, 0, len(paths)+len(genericAPIGlobs))
	for _, glob := range genericAPIGlobs {
		result = append(result, "!"+glob)
	}
	for _, p := range paths {
		result = append(result, "!"+p)
	}
	return result
}

func writeFilters(dest string, docsPaths []string) error {
	var sb strings.Builder
	sb.WriteString("# Generated by `go run ./tools/autogendocslist -filters`. Do not edit.\n")
	sb.WriteString("files:\n")
	sb.WriteString("  - '.changelog/**'\n")
	sb.WriteString("  - 'docs/**'\n")
	for _, p := range negated(docsPaths) {
		fmt.Fprintf(&sb, "  - '%s'\n", p)
	}
	return os.WriteFile(dest, []byte(sb.String()), 0o600)
}

func codeownersBlockText(docsPaths []string) string {
	var sb strings.Builder
	sb.WriteString(beginMarker + "\n")
	sb.WriteString(codeownersEntries(docsPaths))
	sb.WriteString(endMarker + "\n")
	return sb.String()
}

func codeownersEntries(docsPaths []string) string {
	var sb strings.Builder
	for _, glob := range genericAPIGlobs {
		fmt.Fprintf(&sb, "/%s %s\n", glob, docsOwner)
	}
	for _, p := range docsPaths {
		fmt.Fprintf(&sb, "/%s %s\n", p, docsOwner)
	}
	return sb.String()
}

func checkCodeowners(root string) error {
	current, err := os.ReadFile(filepath.Join(root, codeownersPath))
	if err != nil {
		return err
	}
	docsPaths, err := autogenDocsPaths(root)
	if err != nil {
		return err
	}
	expected := codeownersEntries(docsPaths)
	if got := extractCodeownersBlock(string(current)); got != expected {
		return fmt.Errorf("CODEOWNERS autogenerated docs block is outdated, regenerate it with:\n  go run ./tools/autogendocslist -codeowners >> .github/CODEOWNERS\n\nexpected block:\n%s\ngot block:\n%s", expected, got)
	}
	return nil
}

func extractCodeownersBlock(content string) string {
	var lines []string
	inBlock := false
	for line := range strings.SplitSeq(content, "\n") {
		switch {
		case line == beginMarker:
			inBlock = true
		case line == endMarker:
			inBlock = false
		case inBlock:
			lines = append(lines, line+"\n")
		}
	}
	return strings.Join(lines, "")
}
