// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package testname

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "project identifier (aliased from groupId)",
			},
			"project_id_with_tag": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "project identifier with explicit apiname tag",
			},
			"normal_attr": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "normal attribute without APIName",
			},
		},
	}
}

type TFModel struct {
	GroupId          types.String `tfsdk:"project_id" autogen:"omitjson"`
	ProjectIdWithTag types.String `tfsdk:"project_id_with_tag" autogen:"apiname:groupId,omitjson"`
	NormalAttr       types.String `tfsdk:"normal_attr"`
}
