// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package testname

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		DeprecationMessage: "This resource is deprecated. Please use the test_name_new resource instead.",
		Attributes: map[string]schema.Attribute{
			"string_attr": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "string description",
			},
		},
	}
}

type TFModel struct {
	StringAttr types.String `tfsdk:"string_attr"`
}
