// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package testname

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtype"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"first_nested_attr": schema.ListNestedAttribute{
				Optional:            true,
				MarkdownDescription: "first nested attribute",
				CustomType:          customtype.NewNestedListType[TFFirstNestedAttrModel](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"double_nested_list_attr": schema.ListNestedAttribute{
							Optional:            true,
							MarkdownDescription: "double nested list attribute",
							CustomType:          customtype.NewNestedListType[TFDoubleNestedListAttrModel](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"string_attr": schema.StringAttribute{
										Optional:            true,
										MarkdownDescription: "string attribute",
									},
								},
							},
						},
					},
				},
			},
			"second_nested_attr": schema.ListNestedAttribute{
				Optional:            true,
				MarkdownDescription: "second nested attribute",
				CustomType:          customtype.NewNestedListType[TFSecondNestedAttrModel](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"double_nested_list_attr": schema.ListNestedAttribute{
							Optional:            true,
							MarkdownDescription: "double nested list attribute",
							CustomType:          customtype.NewNestedListType[TFDoubleNestedListAttrModel](ctx),
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"string_attr": schema.StringAttribute{
										Optional:            true,
										MarkdownDescription: "string attribute",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

type TFModel struct {
	FirstNestedAttr  customtype.NestedListValue[TFFirstNestedAttrModel]  `tfsdk:"first_nested_attr"`
	SecondNestedAttr customtype.NestedListValue[TFSecondNestedAttrModel] `tfsdk:"second_nested_attr"`
}
type TFFirstNestedAttrModel struct {
	DoubleNestedListAttr customtype.NestedListValue[TFDoubleNestedListAttrModel] `tfsdk:"double_nested_list_attr"`
}
type TFFirstNestedAttrDoubleNestedListAttrModel struct {
	StringAttr types.String `tfsdk:"string_attr"`
}
type TFSecondNestedAttrModel struct {
	DoubleNestedListAttr customtype.NestedListValue[TFDoubleNestedListAttrModel] `tfsdk:"double_nested_list_attr"`
}
type TFSecondNestedAttrDoubleNestedListAttrModel struct {
	StringAttr types.String `tfsdk:"string_attr"`
}
