// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package auditingapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"audit_authorization_success": schema.BoolAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Flag that indicates whether someone set auditing to track successful authentications. This only applies to the `\"atype\" : \"authCheck\"` audit filter. Setting this parameter to `true` degrades cluster performance.",
			},
			"audit_filter": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "JSON document that specifies which events to record. Escape any characters that may prevent parsing, such as single or double quotes, using a backslash (`\\`).",
			},
			"configuration_type": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Human-readable label that displays how to configure the audit filter.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Optional:            true,
				MarkdownDescription: "Flag that indicates whether someone enabled database auditing for the specified project.",
			},
			"group_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.\n\n**NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
		},
	}
}

type TFModel struct {
	AuditFilter               types.String `tfsdk:"audit_filter"`
	ConfigurationType         types.String `tfsdk:"configuration_type" autogen:"omitjson"`
	GroupId                   types.String `tfsdk:"group_id" autogen:"omitjson"`
	AuditAuthorizationSuccess types.Bool   `tfsdk:"audit_authorization_success"`
	Enabled                   types.Bool   `tfsdk:"enabled"`
}
