### List of Realm APIs required for this quickstart.
### This file requires REST Client extension for Visual Studio Code to send requests directly from this file.
### If you are using other IDEs, please add the below APIs to your Postman collection or your favourite REST client application.


### Parameters

### Base URL for the Realm REST APIs.
@baseURL = https://realm.mongodb.com/api/admin/v3.0

### MongoDB public key (acts as the username).
@pubKey = MONGODB_PUBLIC_KEY

### MongoDB private key (acts as the password).
@priKey = MONGODB_PRIVATE_KEY

### Group ID refers to MongoDB project ID.
@groupID = GROUP_ID

@clusterName = CLUSTER_NAME
@appID = REALM_APP_ID
@serviceName = REALM_SERVICE_NAME
@serviceID = REALM_SERVICE_ID

### Access token. Update this once "Get authentication tokens" API is successfully hit.
@accessToken = ACCESS_TOKEN



### Get authentication tokens.
### Ref: https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#section/Get-Authentication-Tokens
POST {{baseURL}}/auth/providers/mongodb-cloud/login
Content-Type: application/json
Accept: application/json'

{
    "username": "{{pubKey}}",
    "apiKey": "{{priKey}}"
}



### List all App Services Apps in an Atlas project/group.
### Ref: https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/apps/operation/adminListApplications
GET {{baseURL}}/groups/{{groupID}}/apps
Authorization: Bearer {{accessToken}}



### Create a new app.
### Ref: https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/apps/operation/adminCreateApplication
POST {{baseURL}}/groups/{{groupID}}/apps
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{clusterName}}-App",
    "data_source": {
        "name": "{{clusterName}}",
        "type": "mongodb-atlas",
        "config": {
            "clusterName": "{{clusterName}}",
            "readPreference": "primary",
            "wireProtocolEnabled": true
        }
    }
}



### List all data sources and third-party services.
### Ref: https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/services/operation/adminListServices
GET {{baseURL}}/groups/{{groupID}}/apps/{{appID}}/services
Authorization: Bearer {{accessToken}}



### Create a service.
### Ref: https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/services/operation/adminCreateService
POST {{baseURL}}/groups/{{groupID}}/apps/{{appID}}/services
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{serviceName}}",
    "type": "mongodb-atlas",
    "config": {
        "clusterName": "{{clusterName}}",
        "readPreference": "primary",
        "wireProtocolEnabled": true
    }
}
