// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package logintegration

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"bucket_name": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Human-readable label that identifies the S3 bucket name for storing log files.",
			},
			"iam_role_id": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies the AWS IAM role that MongoDB Cloud uses to access your S3 bucket.",
			},
			"integration_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique identifier of the log integration configuration.",
			},
			"kms_key": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "AWS KMS key ID or ARN for server-side encryption (optional). If not provided, uses bucket default encryption settings.",
			},
			"log_types": dsschema.SetAttribute{
				Computed:            true,
				MarkdownDescription: "Array of log types exported by this integration. The specific log types available and maximum number of items depend on the integration type. See the integration-specific schema for details.",
				CustomType:          customtypes.NewSetType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"prefix_path": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "S3 directory path prefix where the log files will be stored. MongoDB Cloud will add further sub-directories based on the log type.",
			},
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project. Use the [/groups](#tag/Projects/operation/listProjects) endpoint to retrieve all projects to which the authenticated user has access.\n\n**NOTE**: Groups and projects are synonymous terms. Your group id is the same as your project id. For existing groups, your group/project id remains the same. The resource and corresponding endpoints use the term groups.",
			},
			"region": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Datadog site/region for log ingestion. Valid values: US1, US3, US5, EU, AP1, AP2, US1_FED.",
			},
			"type": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Human-readable label that identifies the service to which you want to integrate with MongoDB Cloud. The value must match the log integration type.",
			},
		},
	}
}

type TFDSModel struct {
	BucketName    types.String                       `tfsdk:"bucket_name" autogen:"omitjson"`
	IamRoleId     types.String                       `tfsdk:"iam_role_id" autogen:"omitjson"`
	IntegrationId types.String                       `tfsdk:"integration_id" apiname:"id" autogen:"omitjson"`
	KmsKey        types.String                       `tfsdk:"kms_key" autogen:"omitjson"`
	LogTypes      customtypes.SetValue[types.String] `tfsdk:"log_types" autogen:"omitjson"`
	PrefixPath    types.String                       `tfsdk:"prefix_path" autogen:"omitjson"`
	ProjectId     types.String                       `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Region        types.String                       `tfsdk:"region" autogen:"omitjson"`
	Type          types.String                       `tfsdk:"type" autogen:"omitjson"`
}
