// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package logintegration

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customvalidator"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: DATADOG_LOG_EXPORT. API key for authentication.",
				Sensitive:           true,
			},
			"bucket_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: GCS_LOG_EXPORT, S3_LOG_EXPORT. Name of the bucket to store log files.",
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"hec_token": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: SPLUNK_LOG_EXPORT. HTTP Event Collector (HEC) token for authentication.",
				Sensitive:           true,
			},
			"hec_url": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: SPLUNK_LOG_EXPORT. HTTP Event Collector (HEC) endpoint URL.",
			},
			"iam_role_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: S3_LOG_EXPORT. Unique 24-character hexadecimal string that identifies the AWS IAM role that Atlas uses to access the S3 bucket.",
			},
			"integration_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unique 24-character hexadecimal digit string that identifies the log integration configuration.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"kms_key": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Optional for type: S3_LOG_EXPORT. AWS KMS key ID or ARN for server-side encryption (optional). If not provided, uses bucket default encryption settings.",
			},
			"log_types": schema.SetAttribute{
				Required:            true,
				MarkdownDescription: "Array of log types exported by this integration.",
				CustomType:          customtypes.NewSetType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"otel_endpoint": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: OTEL_LOG_EXPORT. OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.",
			},
			"otel_supplied_headers": schema.ListNestedAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: OTEL_LOG_EXPORT. HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.",
				Sensitive:           true,
				CustomType:          customtypes.NewNestedListType[TFOtelSuppliedHeadersModel](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Required:            true,
							MarkdownDescription: "Header name.",
						},
						"value": schema.StringAttribute{
							Required:            true,
							MarkdownDescription: "Header value.",
							Sensitive:           true,
						},
					},
				},
			},
			"prefix_path": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: AZURE_LOG_EXPORT, GCS_LOG_EXPORT, S3_LOG_EXPORT. Path prefix where the log files will be stored. Atlas will add further sub-directories based on the log type.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: DATADOG_LOG_EXPORT. Datadog site/region for log ingestion. Valid values: US1, US3, US5, EU, AP1, AP2, US1_FED.",
			},
			"role_id": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: AZURE_LOG_EXPORT, GCS_LOG_EXPORT. Unique 24-character hexadecimal string that identifies the Atlas Cloud Provider Access role.",
			},
			"storage_account_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: AZURE_LOG_EXPORT. Storage account name where logs will be stored.",
			},
			"storage_container_name": schema.StringAttribute{
				Optional:            true,
				MarkdownDescription: "Required for type: AZURE_LOG_EXPORT. Storage container name for log files.",
			},
			"type": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.",
				Validators: []validator.String{
					customvalidator.ValidateDiscriminator(customvalidator.DiscriminatorDefinition{
						Mapping: map[string]customvalidator.VariantDefinition{
							"AZURE_LOG_EXPORT": {
								Allowed:  []string{"prefix_path", "role_id", "storage_account_name", "storage_container_name"},
								Required: []string{"prefix_path", "role_id", "storage_account_name", "storage_container_name"},
							},
							"DATADOG_LOG_EXPORT": {
								Allowed:  []string{"api_key", "region"},
								Required: []string{"api_key", "region"},
							},
							"GCS_LOG_EXPORT": {
								Allowed:  []string{"bucket_name", "prefix_path", "role_id"},
								Required: []string{"bucket_name", "prefix_path", "role_id"},
							},
							"OTEL_LOG_EXPORT": {
								Allowed:  []string{"otel_endpoint", "otel_supplied_headers"},
								Required: []string{"otel_endpoint", "otel_supplied_headers"},
							},
							"S3_LOG_EXPORT": {
								Allowed:  []string{"bucket_name", "iam_role_id", "kms_key", "prefix_path"},
								Required: []string{"bucket_name", "iam_role_id", "prefix_path"},
							},
							"SPLUNK_LOG_EXPORT": {
								Allowed:  []string{"hec_token", "hec_url"},
								Required: []string{"hec_token", "hec_url"},
							},
						},
					}),
				},
			},
		},
	}
}

type TFModel struct {
	ApiKey               types.String                                            `tfsdk:"api_key" autogen:"sensitive"`
	BucketName           types.String                                            `tfsdk:"bucket_name"`
	ProjectId            types.String                                            `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	HecToken             types.String                                            `tfsdk:"hec_token" autogen:"sensitive"`
	HecUrl               types.String                                            `tfsdk:"hec_url"`
	IamRoleId            types.String                                            `tfsdk:"iam_role_id"`
	IntegrationId        types.String                                            `tfsdk:"integration_id" apiname:"id" autogen:"omitjson"`
	KmsKey               types.String                                            `tfsdk:"kms_key"`
	LogTypes             customtypes.SetValue[types.String]                      `tfsdk:"log_types"`
	OtelEndpoint         types.String                                            `tfsdk:"otel_endpoint"`
	OtelSuppliedHeaders  customtypes.NestedListValue[TFOtelSuppliedHeadersModel] `tfsdk:"otel_supplied_headers" autogen:"sensitive"`
	PrefixPath           types.String                                            `tfsdk:"prefix_path"`
	Region               types.String                                            `tfsdk:"region"`
	RoleId               types.String                                            `tfsdk:"role_id"`
	StorageAccountName   types.String                                            `tfsdk:"storage_account_name"`
	StorageContainerName types.String                                            `tfsdk:"storage_container_name"`
	Type                 types.String                                            `tfsdk:"type"`
}
type TFOtelSuppliedHeadersModel struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value" autogen:"sensitive"`
}
