// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package aimodelratelimit

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"model_group_name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The name of the model group to be updated.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"model_names": schema.ListAttribute{
				Computed:            true,
				MarkdownDescription: "List of embedding model names included in this model group.",
				CustomType:          customtypes.NewListType[types.String](ctx),
				ElementType:         types.StringType,
			},
			"requests_per_minute_limit": schema.Int64Attribute{
				Required:            true,
				MarkdownDescription: "The number of requests per minute allowed for this model group. Must be a positive integer. Cannot be more than the organization level limit for this group model.",
			},
			"tokens_per_minute_limit": schema.Int64Attribute{
				Required:            true,
				MarkdownDescription: "The number of tokens per minute allowed for this model group. Must be a positive integer. Cannot be more than the organization level limit for this group model.",
			},
		},
	}
}

type TFModel struct {
	ProjectId              types.String                        `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	ModelGroupName         types.String                        `tfsdk:"model_group_name" autogen:"omitjson"`
	ModelNames             customtypes.ListValue[types.String] `tfsdk:"model_names" autogen:"omitjson"`
	RequestsPerMinuteLimit types.Int64                         `tfsdk:"requests_per_minute_limit"`
	TokensPerMinuteLimit   types.Int64                         `tfsdk:"tokens_per_minute_limit"`
}
