provider:
  name: mongodbatlas

# TODO: Endpoints from Atlas Admin API must be specified for schema and model generation. Singular or plural data sources can be removed if not used.

resources:
  cloud_user_project_assignment:
    read:
      path: /api/atlas/v2/groups/{groupId}/users/{userId}
      method: GET
    create:
      path: /api/atlas/v2/groups/{groupId}/users
      method: POST
    delete:
      path: /api/atlas/v2/groups/{groupId}/users/{userId}
      method: DELETE

