// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package controlplaneipaddressesapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/conversion"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/config"
)

var _ datasource.DataSource = &ds{}
var _ datasource.DataSourceWithConfigure = &ds{}

func DataSource() datasource.DataSource {
	return &ds{
		DSCommon: config.DSCommon{
			DataSourceName: "control_plane_ip_addresses_api",
		},
	}
}

type ds struct {
	config.DSCommon
}

func (d *ds) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = DataSourceSchema(ctx)
	conversion.UpdateSchemaDescription(&resp.Schema)
}

func (d *ds) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var tfConfig TFDSModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &tfConfig)...)
	if resp.Diagnostics.HasError() {
		return
	}
	reqHandle := autogen.HandleDataSourceReadReq{
		Resp:       resp,
		Client:     d.Client,
		Config:     &tfConfig,
		CallParams: dataSourceReadAPICallParams(&tfConfig),
	}
	autogen.HandleDataSourceRead(ctx, reqHandle)
}

func dataSourceReadAPICallParams(model *TFDSModel) *config.APICallParams {
	pathParams := map[string]string{}
	return &config.APICallParams{
		VersionHeader: "application/vnd.atlas.2023-11-15+json",
		RelativePath:  "/api/atlas/v2/unauth/controlPlaneIPAddresses",
		PathParams:    pathParams,
		Method:        "GET",
	}
}
