// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package controlplaneipaddressesapi

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen/customtypes"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"inbound": dsschema.SingleNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of inbound IP addresses to the Atlas control plane, categorized by cloud provider. If your application allows outbound HTTP requests only to specific IP addresses, you must allow access to the following IP addresses so that your API requests can reach the Atlas control plane.",
				CustomType:          customtypes.NewObjectType[TFDSInboundModel](ctx),
				Attributes: map[string]dsschema.Attribute{
					"aws": dsschema.MapAttribute{
						Computed:            true,
						MarkdownDescription: "Control plane IP addresses in AWS. Each key identifies an Amazon Web Services (AWS) region. Each value identifies control plane IP addresses in the AWS region.",
						CustomType:          customtypes.NewMapType[types.String](ctx),
						ElementType:         types.StringType,
					},
					"azure": dsschema.MapAttribute{
						Computed:            true,
						MarkdownDescription: "Control plane IP addresses in Azure. Each key identifies an Azure region. Each value identifies control plane IP addresses in the Azure region.",
						CustomType:          customtypes.NewMapType[types.String](ctx),
						ElementType:         types.StringType,
					},
					"gcp": dsschema.MapAttribute{
						Computed:            true,
						MarkdownDescription: "Control plane IP addresses in GCP. Each key identifies a Google Cloud (GCP) region. Each value identifies control plane IP addresses in the GCP region.",
						CustomType:          customtypes.NewMapType[types.String](ctx),
						ElementType:         types.StringType,
					},
				},
			},
			"outbound": dsschema.SingleNestedAttribute{
				Computed:            true,
				MarkdownDescription: "List of outbound IP addresses from the Atlas control plane, categorized by cloud provider. If your network allows inbound HTTP requests only from specific IP addresses, you must allow access from the following IP addresses so that Atlas can communicate with your webhooks and KMS.",
				CustomType:          customtypes.NewObjectType[TFDSOutboundModel](ctx),
				Attributes: map[string]dsschema.Attribute{
					"aws": dsschema.MapAttribute{
						Computed:            true,
						MarkdownDescription: "Control plane IP addresses in AWS. Each key identifies an Amazon Web Services (AWS) region. Each value identifies control plane IP addresses in the AWS region.",
						CustomType:          customtypes.NewMapType[types.String](ctx),
						ElementType:         types.StringType,
					},
					"azure": dsschema.MapAttribute{
						Computed:            true,
						MarkdownDescription: "Control plane IP addresses in Azure. Each key identifies an Azure region. Each value identifies control plane IP addresses in the Azure region.",
						CustomType:          customtypes.NewMapType[types.String](ctx),
						ElementType:         types.StringType,
					},
					"gcp": dsschema.MapAttribute{
						Computed:            true,
						MarkdownDescription: "Control plane IP addresses in GCP. Each key identifies a Google Cloud (GCP) region. Each value identifies control plane IP addresses in the GCP region.",
						CustomType:          customtypes.NewMapType[types.String](ctx),
						ElementType:         types.StringType,
					},
				},
			},
		},
	}
}

type TFDSModel struct {
	Inbound  customtypes.ObjectValue[TFDSInboundModel]  `tfsdk:"inbound" autogen:"omitjson"`
	Outbound customtypes.ObjectValue[TFDSOutboundModel] `tfsdk:"outbound" autogen:"omitjson"`
}
type TFDSInboundModel struct {
	Aws   customtypes.MapValue[types.String] `tfsdk:"aws" autogen:"omitjson"`
	Azure customtypes.MapValue[types.String] `tfsdk:"azure" autogen:"omitjson"`
	Gcp   customtypes.MapValue[types.String] `tfsdk:"gcp" autogen:"omitjson"`
}
type TFDSOutboundModel struct {
	Aws   customtypes.MapValue[types.String] `tfsdk:"aws" autogen:"omitjson"`
	Azure customtypes.MapValue[types.String] `tfsdk:"azure" autogen:"omitjson"`
	Gcp   customtypes.MapValue[types.String] `tfsdk:"gcp" autogen:"omitjson"`
}
