// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package alertconfigurationapi

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/autogen"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/conversion"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/config"
)

var _ datasource.DataSource = &ds{}
var _ datasource.DataSourceWithConfigure = &ds{}

func DataSource() datasource.DataSource {
	return &ds{
		DSCommon: config.DSCommon{
			DataSourceName: "alert_configuration_api",
		},
	}
}

type ds struct {
	autogen.NoOpCustomCodeHooks
	config.DSCommon
}

func (d *ds) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = DataSourceSchema(ctx)
	conversion.UpdateSchemaDescription(&resp.Schema)
}

func (d *ds) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var tfConfig TFDSModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &tfConfig)...)
	if resp.Diagnostics.HasError() {
		return
	}
	reqHandle := autogen.HandleReadReq{
		ReadAPICallHooks: d,
		RespDiags:        &resp.Diagnostics,
		RespState:        &resp.State,
		Client:           d.Client,
		State:            &tfConfig,
		CallParams:       dataSourceReadAPICallParams(&tfConfig),
	}
	autogen.HandleDataSourceRead(ctx, reqHandle)
}

func dataSourceReadAPICallParams(model *TFDSModel) *config.APICallParams {
	pathParams := map[string]string{
		"groupId": model.GroupId.ValueString(),
		"id":      model.Id.ValueString(),
	}
	return &config.APICallParams{
		VersionHeader: "application/vnd.atlas.2023-01-01+json",
		RelativePath:  "/api/atlas/v2/groups/{groupId}/alertConfigs/{id}",
		PathParams:    pathParams,
		Method:        "GET",
	}
}
