#!/bin/bash

set -e

# Cleanup temp file on script exit
trap 'rm -f "$TEMP_FILE"' EXIT

cd "$(dirname "$0")/.."

OPENAPI_URL="https://raw.githubusercontent.com/mongodb/openapi/refs/heads/main/openapi/v2.yaml"
TEMP_FILE=$(mktemp)

curl -s "$OPENAPI_URL" |
  yq '(.security) = []' -o=json > "$TEMP_FILE"

echo "==> Starting mock server"

# Run prism mock on the given spec
if [ "$1" == "--daemon" ]; then
  npx @stoplight/prism-cli mock "$TEMP_FILE" &> .prism.log &

  # Wait for server to come online
  echo -n "Waiting for server"
  while ! grep -q "✖  fatal\|Prism is listening" ".prism.log" ; do
    echo -n "."
    sleep 0.1
  done

  if grep -q "✖  fatal" ".prism.log"; then
    cat .prism.log
    exit 1
  fi

  echo
else
  npx @stoplight/prism-cli mock "$TEMP_FILE"
fi