provider:
  name: mongodbatlas

# TODO: Endpoints from Atlas Admin API must be specified for schema and model generation. Singular or plural data sources can be removed if not used.

resources:
  push_based_log_export:
    read:
      path: /api/atlas/v2/groups/{groupId}/pushBasedLogExport
      method: GET
    create:
      path: /api/atlas/v2/groups/{groupId}/pushBasedLogExport
      method: POST
    update:
      path: /api/atlas/v2/groups/{groupId}/pushBasedLogExport
      method: PATCH
    delete:
      path: /api/atlas/v2/groups/{groupId}/pushBasedLogExport
      method: DELETE

data_sources:
  push_based_log_export:
    read:
      path: /api/atlas/v2/groups/{groupId}/pushBasedLogExport
      method: GET
