package main

import (
	"strings"
	"testing"

	"github.com/mongodb/terraform-provider-mongodbatlas/tools/codegen/codespec"
)

func disc(propName string, mapping map[string]codespec.DiscriminatorType) *codespec.Discriminator {
	return &codespec.Discriminator{
		PropertyName: codespec.DiscriminatorAttrName{APIName: propName, TFSchemaName: propName},
		Mapping:      mapping,
	}
}

func attrName(name string) codespec.DiscriminatorAttrName {
	return codespec.DiscriminatorAttrName{APIName: name, TFSchemaName: name}
}

func TestRestructure_ResourceOptionalSection(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"DATADOG": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("api_key"), attrName("region")},
				Required: []codespec.DiscriminatorAttrName{attrName("api_key"), attrName("region")},
			},
			"GCS": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("bucket_name")},
				Required: []codespec.DiscriminatorAttrName{attrName("bucket_name")},
			},
			"S3": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("bucket_name"), attrName("kms_key")},
				Required: []codespec.DiscriminatorAttrName{attrName("bucket_name")},
			},
		}),
	}

	input := lines(
		"---",
		`subcategory: "Log Integration"`,
		"---",
		"",
		"# Resource: mongodbatlas_log_integration",
		"",
		"Some description text.",
		"",
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `log_types` (Set of String) Array of log types.",
		"- `project_id` (String) Unique ID.",
		"- `type` (String) The type discriminator.",
		"",
		"### Optional",
		"",
		"- `api_key` (String, Sensitive) API key for auth.",
		"- `bucket_name` (String) Name of the bucket.",
		"- `kms_key` (String) AWS KMS key ID.",
		"- `region` (String) Datadog region.",
		"",
		"### Read-Only",
		"",
		"- `integration_id` (String) Unique ID.",
		"",
		"## Import",
		"",
		"Import instructions here.",
		"",
	)

	expected := lines(
		"---",
		`subcategory: "Log Integration"`,
		"---",
		"",
		"# Resource: mongodbatlas_log_integration",
		"",
		"Some description text.",
		"",
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `log_types` (Set of String) Array of log types.",
		"- `project_id` (String) Unique ID.",
		"- `type` (String) The type discriminator.",
		"",
		"### Optional",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `DATADOG`",
		"",
		"- `api_key` (String, Sensitive) **Required.** API key for auth.",
		"- `region` (String) **Required.** Datadog region.",
		"",
		"#### `GCS`",
		"",
		"- `bucket_name` (String) **Required.** Name of the bucket.",
		"",
		"#### `S3`",
		"",
		"- `bucket_name` (String) **Required.** Name of the bucket.",
		"- `kms_key` (String) AWS KMS key ID.",
		"",
		"### Read-Only",
		"",
		"- `integration_id` (String) Unique ID.",
		"",
		"## Import",
		"",
		"Import instructions here.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, true)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_DataSourceReadOnlySection(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"DATADOG": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("api_key")},
				Required: []codespec.DiscriminatorAttrName{attrName("api_key")},
			},
			"GCS": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("bucket_name")},
				Required: []codespec.DiscriminatorAttrName{attrName("bucket_name")},
			},
			"S3": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("bucket_name")},
				Required: []codespec.DiscriminatorAttrName{attrName("bucket_name")},
			},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `integration_id` (String) Unique ID.",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `api_key` (String, Sensitive) API key.",
		"- `bucket_name` (String) Bucket name.",
		"- `log_types` (Set of String) Log types.",
		"- `type` (String) The type value.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `integration_id` (String) Unique ID.",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `log_types` (Set of String) Log types.",
		"- `type` (String) The type value.",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `DATADOG`",
		"",
		"- `api_key` (String, Sensitive) API key.",
		"",
		"#### `GCS`",
		"",
		"- `bucket_name` (String) Bucket name.",
		"",
		"#### `S3`",
		"",
		"- `bucket_name` (String) Bucket name.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, false)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_NestedSchemaWithPolymorphic(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"results": disc("type", map[string]codespec.DiscriminatorType{
			"DATADOG": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("api_key"), attrName("region")},
				Required: []codespec.DiscriminatorAttrName{attrName("api_key"), attrName("region")},
			},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `results` (Attributes List) Results list. (see [below for nested schema](#nestedatt--results))",
		"",
		`<a id="nestedatt--results"></a>`,
		"### Nested Schema for `results`",
		"",
		"Read-Only:",
		"",
		"- `api_key` (String) API key.",
		"- `integration_id` (String) Unique ID.",
		"- `region` (String) Region.",
		"- `type` (String) Type value.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `results` (Attributes List) Results list. (see [below for nested schema](#nestedatt--results))",
		"",
		`<a id="nestedatt--results"></a>`,
		"### Nested Schema for `results`",
		"",
		"Read-Only:",
		"",
		"- `integration_id` (String) Unique ID.",
		"- `type` (String) Type value.",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `DATADOG`",
		"",
		"- `api_key` (String) API key.",
		"- `region` (String) Region.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, false)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_MixedRequiredAndApplicable(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"ALPHA": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("shared_attr"), attrName("only_alpha")},
				Required: []codespec.DiscriminatorAttrName{attrName("only_alpha")},
			},
			"BETA": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("shared_attr")},
				Required: []codespec.DiscriminatorAttrName{attrName("shared_attr")},
			},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `shared_attr` (String) Shared attribute desc.",
		"- `only_alpha` (String) Alpha only desc.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `ALPHA`",
		"",
		"- `only_alpha` (String) **Required.** Alpha only desc.",
		"- `shared_attr` (String) Shared attribute desc.",
		"",
		"#### `BETA`",
		"",
		"- `shared_attr` (String) **Required.** Shared attribute desc.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, true)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_NoPolymorphicAttrs(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"ALPHA": {
				Allowed: []codespec.DiscriminatorAttrName{attrName("special_attr")},
			},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `project_id` (String) Project ID.",
		"- `name` (String) Resource name.",
		"",
		"### Optional",
		"",
		"- `description` (String) A description.",
		"",
		"### Read-Only",
		"",
		"- `id` (String) Unique ID.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, true)
	if result != input {
		t.Errorf("expected no changes for non-polymorphic doc.\n\nGot:\n---\n%s\n---\n\nInput:\n---\n%s\n---", result, input)
	}
}

func TestRestructure_Idempotency(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"DATADOG": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("api_key")},
				Required: []codespec.DiscriminatorAttrName{attrName("api_key")},
			},
			"S3": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("bucket")},
				Required: []codespec.DiscriminatorAttrName{attrName("bucket")},
			},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `api_key` (String, Sensitive) API key.",
		"- `bucket` (String) Bucket name.",
		"",
	)

	first := RestructurePolymorphicDocs(input, discriminators, true)
	second := RestructurePolymorphicDocs(first, discriminators, true)

	if first != second {
		t.Errorf("not idempotent.\n\nFirst pass:\n---\n%s\n---\n\nSecond pass:\n---\n%s\n---", first, second)
	}
}

func TestRestructure_CommonAndPolymorphicMixed(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"ALPHA": {
				Allowed:  []codespec.DiscriminatorAttrName{attrName("type_specific")},
				Required: []codespec.DiscriminatorAttrName{attrName("type_specific")},
			},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `common_attr` (String) A common optional attribute.",
		"- `type_specific` (String) Type specific desc.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `common_attr` (String) A common optional attribute.",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `ALPHA`",
		"",
		"- `type_specific` (String) **Required.** Type specific desc.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, true)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_NestedSchemaUnchangedPreserved(t *testing.T) {
	discriminators := map[string]*codespec.Discriminator{
		"": disc("type", map[string]codespec.DiscriminatorType{
			"ALPHA": {Allowed: []codespec.DiscriminatorAttrName{attrName("some_attr")}},
		}),
	}

	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `name` (String) Name.",
		"",
		`<a id="nestedatt--settings"></a>`,
		"### Nested Schema for `settings`",
		"",
		"Required:",
		"",
		"- `enabled` (Boolean) Whether enabled.",
		"",
		"Read-Only:",
		"",
		"- `status` (String) Current status.",
		"",
	)

	result := RestructurePolymorphicDocs(input, discriminators, true)
	if result != input {
		t.Errorf("expected no changes for nested schema without polymorphic attrs.\n\nGot:\n---\n%s\n---\n\nInput:\n---\n%s\n---", result, input)
	}
}

func TestClassifyAttributes_AllCommon(t *testing.T) {
	d := disc("type", map[string]codespec.DiscriminatorType{
		"A": {Allowed: []codespec.DiscriminatorAttrName{attrName("x")}},
	})
	attrs := []parsedAttribute{
		{name: "type", typeInfo: "String", description: "Type.", rawLine: "- `type` (String) Type."},
		{name: "unrelated", typeInfo: "String", description: "Unrelated.", rawLine: "- `unrelated` (String) Unrelated."},
	}

	common, typeGroups := classifyAttributes(attrs, d, true)

	if len(common) != 2 {
		t.Errorf("expected 2 common attrs, got %d", len(common))
	}
	if len(typeGroups) != 0 {
		t.Errorf("expected 0 type groups, got %d", len(typeGroups))
	}
}

func TestClassifyAttributes_RequiredAndOptional(t *testing.T) {
	d := disc("type", map[string]codespec.DiscriminatorType{
		"A": {
			Allowed:  []codespec.DiscriminatorAttrName{attrName("x"), attrName("y")},
			Required: []codespec.DiscriminatorAttrName{attrName("x")},
		},
	})
	attrs := []parsedAttribute{
		{name: "x", typeInfo: "String", description: "X attr.", rawLine: "- `x` (String) X attr."},
		{name: "y", typeInfo: "String", description: "Y attr.", rawLine: "- `y` (String) Y attr."},
	}

	common, typeGroups := classifyAttributes(attrs, d, true)

	if len(common) != 0 {
		t.Errorf("expected 0 common attrs, got %d", len(common))
	}
	entries, ok := typeGroups["A"]
	if !ok || len(entries) != 2 {
		t.Fatalf("expected 2 entries for A, got %v", typeGroups)
	}

	var xEntry, yEntry *typeEntry
	for i := range entries {
		switch entries[i].attr.name {
		case "x":
			xEntry = &entries[i]
		case "y":
			yEntry = &entries[i]
		}
	}
	if xEntry == nil || !xEntry.isRequired {
		t.Error("expected x to be required")
	}
	if yEntry == nil || yEntry.isRequired {
		t.Error("expected y to not be required")
	}
}

func TestClassifyAttributes_DataSourceNeverRequired(t *testing.T) {
	d := disc("type", map[string]codespec.DiscriminatorType{
		"A": {
			Allowed:  []codespec.DiscriminatorAttrName{attrName("x")},
			Required: []codespec.DiscriminatorAttrName{attrName("x")},
		},
	})
	attrs := []parsedAttribute{
		{name: "x", typeInfo: "String", description: "X attr.", rawLine: "- `x` (String) X attr."},
	}

	_, typeGroups := classifyAttributes(attrs, d, false)

	entries := typeGroups["A"]
	if len(entries) != 1 {
		t.Fatalf("expected 1 entry for A, got %d", len(entries))
	}
	if entries[0].isRequired {
		t.Error("expected x to NOT be required for data source")
	}
}

func lines(l ...string) string {
	return strings.Join(l, "\n")
}
