package main

import (
	"fmt"
	"regexp"
	"slices"
	"strings"

	"github.com/mongodb/terraform-provider-mongodbatlas/tools/codegen/codespec"
)

const tfplugindocsMarker = "<!-- schema generated by tfplugindocs -->"

var (
	attrLineRegex         = regexp.MustCompile("^- `([^`]+)` \\(([^)]+)\\) (.+)$")
	prefixRegex           = regexp.MustCompile(`^(` + codespec.DescriptionPrefixRequired + `|` + codespec.DescriptionPrefixOptional + `|` + codespec.DescriptionPrefixApplies + `) (\w+): ([^.]+)\.\s*`)
	topSectionRegex       = regexp.MustCompile(`^### (Required|Optional|Read-Only)$`)
	nestedSubSectionRegex = regexp.MustCompile(`^(Required|Optional|Read-Only):$`)
)

type parsedPrefix struct {
	discriminator string
	types         []string
	isRequired    bool
}

// parsedAttribute holds the decomposition of a markdown attribute entry.
// name, typeInfo, prefixes, and description are parsed from the first source line;
// sourceLines preserves all original lines (including continuation lines) for verbatim output.
type parsedAttribute struct {
	name        string
	typeInfo    string
	description string
	sourceLines []string
	prefixes    []parsedPrefix
}

func (a *parsedAttribute) isPolymorphic() bool {
	return len(a.prefixes) > 0
}

type typeEntry struct {
	attr       parsedAttribute
	isRequired bool
}

type replacement struct {
	newContent []string
	startLine  int
	endLine    int
}

// RestructurePolymorphicDocs processes a full markdown document, restructuring
// only the specific sections that contain polymorphic attribute prefixes.
// All other content is preserved exactly as-is.
func RestructurePolymorphicDocs(content string) string {
	if !strings.Contains(content, tfplugindocsMarker) {
		return content
	}

	lines := strings.Split(content, "\n")
	markerIdx := findMarkerIndex(lines)
	if markerIdx == -1 {
		return content
	}

	schemaEnd := findSchemaEnd(lines, markerIdx)
	replacements := findReplacements(lines, markerIdx, schemaEnd)

	if len(replacements) == 0 {
		return content
	}

	return applyReplacements(lines, replacements)
}

func findMarkerIndex(lines []string) int {
	for i, line := range lines {
		if strings.TrimSpace(line) == tfplugindocsMarker {
			return i
		}
	}
	return -1
}

// findSchemaEnd returns the line index of the first level-2 heading after "## Schema"
// (typically "## Import" for resources). For data sources the schema extends to EOF.
func findSchemaEnd(lines []string, markerIdx int) int {
	for i := markerIdx + 1; i < len(lines); i++ {
		line := lines[i]
		if strings.HasPrefix(line, "## ") && line != "## Schema" {
			return i
		}
	}
	return len(lines)
}

// findReplacements scans the schema portion for attribute list regions that
// contain polymorphic prefixes. For each such region, it builds a replacement.
func findReplacements(lines []string, start, end int) []replacement {
	var replacements []replacement

	i := start
	for i < end {
		line := lines[i]

		if topSectionRegex.MatchString(line) || nestedSubSectionRegex.MatchString(line) {
			attrStart, attrEnd, attrs := collectAttributeBlock(lines, i+1, end)
			if hasPolymorphicAttrs(attrs) {
				replacements = append(replacements, replacement{
					startLine:  attrStart,
					endLine:    attrEnd,
					newContent: buildRestructuredBlock(attrs),
				})
			}
			i = attrEnd
			continue
		}
		i++
	}

	return replacements
}

// collectAttributeBlock finds the contiguous block of attribute lines (with
// interleaved blank lines and multiline continuations) after a section heading.
func collectAttributeBlock(lines []string, afterHeading, schemaEnd int) (attrStart, attrEnd int, attrs []parsedAttribute) {
	i := afterHeading
	for i < schemaEnd && strings.TrimSpace(lines[i]) == "" {
		i++
	}
	attrStart = i

	lastContentIdx := i
	var pendingBlanks []string
	for i < schemaEnd {
		line := lines[i]
		if m := attrLineRegex.FindStringSubmatch(line); m != nil {
			pendingBlanks = nil
			attrs = append(attrs, parseAttributeLine(m))
			lastContentIdx = i + 1
			i++
			continue
		}
		if strings.TrimSpace(line) == "" {
			pendingBlanks = append(pendingBlanks, line)
			i++
			continue
		}
		if len(attrs) > 0 && !isSectionBoundary(line) {
			last := &attrs[len(attrs)-1]
			last.sourceLines = append(last.sourceLines, pendingBlanks...)
			last.sourceLines = append(last.sourceLines, line)
			pendingBlanks = nil
			lastContentIdx = i + 1
			i++
			continue
		}
		break
	}
	attrEnd = lastContentIdx
	return attrStart, attrEnd, attrs
}

func parseAttributeLine(match []string) parsedAttribute {
	prefixes, description := extractPrefixes(match[3])
	return parsedAttribute{
		name:        match[1],
		typeInfo:    match[2],
		sourceLines: []string{match[0]},
		prefixes:    prefixes,
		description: description,
	}
}

func isSectionBoundary(line string) bool {
	return strings.HasPrefix(line, "#") || strings.HasPrefix(line, "<a ") ||
		nestedSubSectionRegex.MatchString(line)
}

func extractPrefixes(desc string) (prefixes []parsedPrefix, remaining string) {
	remaining = desc
	for range 2 {
		m := prefixRegex.FindStringSubmatch(remaining)
		if m == nil {
			break
		}
		prefixes = append(prefixes, parsedPrefix{
			discriminator: m[2],
			types:         splitAndTrim(m[3]),
			isRequired:    m[1] == codespec.DescriptionPrefixRequired,
		})
		remaining = prefixRegex.ReplaceAllString(remaining, "")
	}
	return prefixes, remaining
}

func splitAndTrim(s string) []string {
	var result []string
	for p := range strings.SplitSeq(s, ",") {
		if t := strings.TrimSpace(p); t != "" {
			result = append(result, t)
		}
	}
	return result
}

func hasPolymorphicAttrs(attrs []parsedAttribute) bool {
	for _, attr := range attrs {
		if attr.isPolymorphic() {
			return true
		}
	}
	return false
}

// buildRestructuredBlock builds the replacement lines for a polymorphic attribute
// block. Common attributes are listed first (preserving original lines), then
// type-grouped subsections follow.
func buildRestructuredBlock(attrs []parsedAttribute) []string {
	common, typeGroups := groupByType(attrs)
	discriminator := findDiscriminatorName(attrs)

	var result []string
	for _, attr := range common {
		result = append(result, attr.sourceLines...)
	}

	if len(common) > 0 {
		result = append(result, "")
	}
	result = append(result, fmt.Sprintf("The following attributes depend on the value of `%s`:", discriminator))

	for _, typeName := range sortedTypeKeys(typeGroups) {
		result = append(result, "", fmt.Sprintf("#### `%s`", typeName), "")

		entries := typeGroups[typeName]
		slices.SortFunc(entries, func(a, b typeEntry) int {
			return strings.Compare(a.attr.name, b.attr.name)
		})
		for i := range entries {
			result = append(result, renderTypeAttribute(&entries[i])...)
		}
	}

	return result
}

func findDiscriminatorName(attrs []parsedAttribute) string {
	for _, attr := range attrs {
		for _, prefix := range attr.prefixes {
			return prefix.discriminator
		}
	}
	return "type"
}

func groupByType(attrs []parsedAttribute) (common []parsedAttribute, typeGroups map[string][]typeEntry) {
	typeGroups = make(map[string][]typeEntry)
	for _, attr := range attrs {
		if !attr.isPolymorphic() {
			common = append(common, attr)
			continue
		}
		for _, prefix := range attr.prefixes {
			for _, typeName := range prefix.types {
				typeGroups[typeName] = append(typeGroups[typeName], typeEntry{
					attr:       attr,
					isRequired: prefix.isRequired,
				})
			}
		}
	}
	return common, typeGroups
}

func sortedTypeKeys(m map[string][]typeEntry) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	return keys
}

func renderTypeAttribute(entry *typeEntry) []string {
	desc := entry.attr.description
	if entry.isRequired {
		desc = "**Required.** " + desc
	}
	lines := []string{fmt.Sprintf("- `%s` (%s) %s", entry.attr.name, entry.attr.typeInfo, desc)}
	lines = append(lines, entry.attr.sourceLines[1:]...)
	return lines
}

func applyReplacements(lines []string, replacements []replacement) string {
	for i := len(replacements) - 1; i >= 0; i-- {
		r := replacements[i]
		var newLines []string
		newLines = append(newLines, lines[:r.startLine]...)
		newLines = append(newLines, r.newContent...)
		newLines = append(newLines, lines[r.endLine:]...)
		lines = newLines
	}
	return strings.Join(lines, "\n")
}
