package main

import (
	"strings"
	"testing"
)

func TestRestructure_ResourceOptionalSection(t *testing.T) {
	input := lines(
		"---",
		`subcategory: "Log Integration"`,
		"---",
		"",
		"# Resource: mongodbatlas_log_integration",
		"",
		"Some description text.",
		"",
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `log_types` (Set of String) Array of log types.",
		"- `project_id` (String) Unique ID.",
		"- `type` (String) The type discriminator.",
		"",
		"### Optional",
		"",
		"- `api_key` (String, Sensitive) Required for type: DATADOG. API key for auth.",
		"- `bucket_name` (String) Required for type: GCS, S3. Name of the bucket.",
		"- `kms_key` (String) Applies to type: S3. AWS KMS key ID.",
		"- `region` (String) Required for type: DATADOG. Datadog region.",
		"",
		"### Read-Only",
		"",
		"- `integration_id` (String) Unique ID.",
		"",
		"## Import",
		"",
		"Import instructions here.",
		"",
	)

	expected := lines(
		"---",
		`subcategory: "Log Integration"`,
		"---",
		"",
		"# Resource: mongodbatlas_log_integration",
		"",
		"Some description text.",
		"",
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `log_types` (Set of String) Array of log types.",
		"- `project_id` (String) Unique ID.",
		"- `type` (String) The type discriminator.",
		"",
		"### Optional",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `DATADOG`",
		"",
		"- `api_key` (String, Sensitive) **Required.** API key for auth.",
		"- `region` (String) **Required.** Datadog region.",
		"",
		"#### `GCS`",
		"",
		"- `bucket_name` (String) **Required.** Name of the bucket.",
		"",
		"#### `S3`",
		"",
		"- `bucket_name` (String) **Required.** Name of the bucket.",
		"- `kms_key` (String) AWS KMS key ID.",
		"",
		"### Read-Only",
		"",
		"- `integration_id` (String) Unique ID.",
		"",
		"## Import",
		"",
		"Import instructions here.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_DataSourceReadOnlySection(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `integration_id` (String) Unique ID.",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `api_key` (String, Sensitive) Applies to type: DATADOG. API key.",
		"- `bucket_name` (String) Applies to type: GCS, S3. Bucket name.",
		"- `log_types` (Set of String) Log types.",
		"- `type` (String) The type value.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `integration_id` (String) Unique ID.",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `log_types` (Set of String) Log types.",
		"- `type` (String) The type value.",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `DATADOG`",
		"",
		"- `api_key` (String, Sensitive) API key.",
		"",
		"#### `GCS`",
		"",
		"- `bucket_name` (String) Bucket name.",
		"",
		"#### `S3`",
		"",
		"- `bucket_name` (String) Bucket name.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_NestedSchemaWithPolymorphic(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `results` (Attributes List) Results list. (see [below for nested schema](#nestedatt--results))",
		"",
		`<a id="nestedatt--results"></a>`,
		"### Nested Schema for `results`",
		"",
		"Read-Only:",
		"",
		"- `api_key` (String) Applies to type: DATADOG. API key.",
		"- `integration_id` (String) Unique ID.",
		"- `region` (String) Applies to type: DATADOG. Region.",
		"- `type` (String) Type value.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `project_id` (String) Project ID.",
		"",
		"### Read-Only",
		"",
		"- `results` (Attributes List) Results list. (see [below for nested schema](#nestedatt--results))",
		"",
		`<a id="nestedatt--results"></a>`,
		"### Nested Schema for `results`",
		"",
		"Read-Only:",
		"",
		"- `integration_id` (String) Unique ID.",
		"- `type` (String) Type value.",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `DATADOG`",
		"",
		"- `api_key` (String) API key.",
		"- `region` (String) Region.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_MixedRequiredAndApplicable(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `shared_attr` (String) Required for type: BETA. Applies to type: ALPHA. Shared attribute desc.",
		"- `only_alpha` (String) Required for type: ALPHA. Alpha only desc.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `ALPHA`",
		"",
		"- `only_alpha` (String) **Required.** Alpha only desc.",
		"- `shared_attr` (String) Shared attribute desc.",
		"",
		"#### `BETA`",
		"",
		"- `shared_attr` (String) **Required.** Shared attribute desc.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_NoPolymorphicAttrs(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `project_id` (String) Project ID.",
		"- `name` (String) Resource name.",
		"",
		"### Optional",
		"",
		"- `description` (String) A description.",
		"",
		"### Read-Only",
		"",
		"- `id` (String) Unique ID.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != input {
		t.Errorf("expected no changes for non-polymorphic doc.\n\nGot:\n---\n%s\n---\n\nInput:\n---\n%s\n---", result, input)
	}
}

func TestRestructure_NoTfplugindocsMarker(t *testing.T) {
	input := lines(
		"# Resource: mongodbatlas_stream_connection",
		"",
		"Manually maintained docs.",
		"",
		"## Argument Reference",
		"",
		"* `type` - (Required) Connection type.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != input {
		t.Errorf("expected no changes for file without marker.\n\nGot:\n---\n%s\n---", result)
	}
}

func TestRestructure_Idempotency(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `api_key` (String, Sensitive) Required for type: DATADOG. API key.",
		"- `bucket` (String) Required for type: S3. Bucket name.",
		"",
	)

	first := RestructurePolymorphicDocs(input)
	second := RestructurePolymorphicDocs(first)

	if first != second {
		t.Errorf("not idempotent.\n\nFirst pass:\n---\n%s\n---\n\nSecond pass:\n---\n%s\n---", first, second)
	}
}

func TestRestructure_CommonAndPolymorphicMixed(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `common_attr` (String) A common optional attribute.",
		"- `type_specific` (String) Required for type: ALPHA. Type specific desc.",
		"",
	)

	expected := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Optional",
		"",
		"- `common_attr` (String) A common optional attribute.",
		"",
		"The following attributes depend on the value of `type`:",
		"",
		"#### `ALPHA`",
		"",
		"- `type_specific` (String) **Required.** Type specific desc.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != expected {
		t.Errorf("mismatch.\n\nGot:\n---\n%s\n---\n\nExpected:\n---\n%s\n---", result, expected)
	}
}

func TestRestructure_NestedSchemaUnchangedPreserved(t *testing.T) {
	input := lines(
		"<!-- schema generated by tfplugindocs -->",
		"## Schema",
		"",
		"### Required",
		"",
		"- `name` (String) Name.",
		"",
		`<a id="nestedatt--settings"></a>`,
		"### Nested Schema for `settings`",
		"",
		"Required:",
		"",
		"- `enabled` (Boolean) Whether enabled.",
		"",
		"Read-Only:",
		"",
		"- `status` (String) Current status.",
		"",
	)

	result := RestructurePolymorphicDocs(input)
	if result != input {
		t.Errorf("expected no changes for nested schema without polymorphic attrs.\n\nGot:\n---\n%s\n---\n\nInput:\n---\n%s\n---", result, input)
	}
}

func TestExtractPrefixes_RequiredOnly(t *testing.T) {
	prefixes := extractPrefixes("Required for type: S3_LOG_EXPORT. Bucket name.")

	if len(prefixes) != 1 {
		t.Fatalf("expected 1 prefix, got %d", len(prefixes))
	}
	if !prefixes[0].isRequired {
		t.Error("expected isRequired=true")
	}
	if prefixes[0].discriminator != "type" {
		t.Errorf("expected discriminator=type, got %s", prefixes[0].discriminator)
	}
	if len(prefixes[0].types) != 1 || prefixes[0].types[0] != "S3_LOG_EXPORT" {
		t.Errorf("unexpected types: %v", prefixes[0].types)
	}
}

func TestExtractPrefixes_ApplicableMultipleTypes(t *testing.T) {
	prefixes := extractPrefixes("Applies to type: S3, GCS. Description.")

	if len(prefixes) != 1 {
		t.Fatalf("expected 1 prefix, got %d", len(prefixes))
	}
	if prefixes[0].isRequired {
		t.Error("expected isRequired=false")
	}
	if len(prefixes[0].types) != 2 || prefixes[0].types[0] != "S3" || prefixes[0].types[1] != "GCS" {
		t.Errorf("unexpected types: %v", prefixes[0].types)
	}
}

func TestExtractPrefixes_BothRequiredAndApplicable(t *testing.T) {
	prefixes := extractPrefixes("Required for type: BETA. Applies to type: ALPHA. Description.")

	if len(prefixes) != 2 {
		t.Fatalf("expected 2 prefixes, got %d", len(prefixes))
	}
	if !prefixes[0].isRequired {
		t.Error("first prefix should be required")
	}
	if prefixes[1].isRequired {
		t.Error("second prefix should be applicable")
	}
}

func TestExtractPrefixes_NoPrefix(t *testing.T) {
	prefixes := extractPrefixes("A normal description without any prefix.")

	if len(prefixes) != 0 {
		t.Errorf("expected 0 prefixes, got %d", len(prefixes))
	}
}

func lines(l ...string) string {
	return strings.Join(l, "\n")
}
