# Export Atlas metrics to an OTLP-compatible endpoint using OAuth 2.0 private-key JWT authentication.
resource "mongodbatlas_project" "this" {
  name   = var.atlas_project_name
  org_id = var.atlas_org_id
}

resource "mongodbatlas_metric_integration" "example" {
  project_id              = mongodbatlas_project.this.id
  integration_type        = "OTEL"
  provider_type           = "CUSTOM"
  auth_type               = "OAUTH2"
  aggregation_temporality = "DELTA"
  endpoint                = var.otel_endpoint
  metric_selection        = var.metric_selection

  oauth = {
    client_auth_method   = "PRIVATE_KEY_JWT"
    token_endpoint       = var.token_endpoint
    client_id            = var.client_id
    token_request_params = var.token_request_params
  }
}

data "mongodbatlas_metric_integration" "example" {
  project_id            = mongodbatlas_metric_integration.example.project_id
  metric_integration_id = mongodbatlas_metric_integration.example.metric_integration_id
}

data "mongodbatlas_metric_integrations" "example" {
  project_id = mongodbatlas_metric_integration.example.project_id
  depends_on = [mongodbatlas_metric_integration.example]
}

output "metric_integration_type" {
  description = "Type of the metric integration."
  value       = data.mongodbatlas_metric_integration.example.integration_type
}

output "metric_integration_ids" {
  description = "IDs of the metric integrations in the project."
  value       = [for r in data.mongodbatlas_metric_integrations.example.results : r.metric_integration_id]
}

output "signing_key_info" {
  description = "Read-only signing key metadata generated by Atlas. Register the jwks_uri with your identity provider."
  value       = data.mongodbatlas_metric_integration.example.oauth.signing_key_info
}
