// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package aimodelapikey

import (
	"context"

	dsschema "github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

func DataSourceSchema(ctx context.Context) dsschema.Schema {
	return dsschema.Schema{
		Attributes: map[string]dsschema.Attribute{
			"api_key_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The id of the API key to be retrieved.",
			},
			"created_at": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC date when the API key was created. This parameter is formatted as an ISO 8601 timestamp.",
			},
			"created_by": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Name of the user that created this API key. If no user name is available, the user ID is returned.",
			},
			"last_used_at": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "UTC date when the API key was last used. This parameter is formatted as an ISO 8601 timestamp.",
			},
			"masked_secret": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "A partially obfuscated version of the API key secret returned when the API key was created.",
			},
			"name": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Arbitrary string identifier assigned to this API key for convenient identification.",
			},
			"project_id": dsschema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project.",
			},
			"status": dsschema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "A string describing the current status of the API key.",
			},
		},
	}
}

type TFDSModel struct {
	ApiKeyId     types.String `tfsdk:"api_key_id" autogen:"omitjson"`
	CreatedAt    types.String `tfsdk:"created_at" autogen:"omitjson"`
	CreatedBy    types.String `tfsdk:"created_by" autogen:"omitjson"`
	LastUsedAt   types.String `tfsdk:"last_used_at" autogen:"omitjson"`
	MaskedSecret types.String `tfsdk:"masked_secret" autogen:"omitjson"`
	Name         types.String `tfsdk:"name" autogen:"omitjson"`
	ProjectId    types.String `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Status       types.String `tfsdk:"status" autogen:"omitjson"`
}
