// Code generated by terraform-provider-mongodbatlas using `make generate-resource`. DO NOT EDIT.

package aimodelapikey

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/mongodb/terraform-provider-mongodbatlas/internal/common/customplanmodifier"
)

func ResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Identifier used to reference this API key in admin API calls.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"cloud": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Cloud provider scope for this API key. Must be \"ANY\". Additional cloud values will be supported in future API versions.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"geography": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Geography scope for this API key. Must be \"ANY\". Additional geography values will be supported in future API versions.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.",
				PlanModifiers:       []planmodifier.String{customplanmodifier.CreateOnly()},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "A name for the new API key that will be created.",
			},
			"secret": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The full API key secret used for interacting with the embedding / reranking service. Note: this will only be fully populated in the response to a create API key request. Responses to get, list, and update requests will not include the secret.",
				Sensitive:           true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

type TFModel struct {
	ApiKeyId  types.String `tfsdk:"api_key_id" autogen:"omitjson"`
	Cloud     types.String `tfsdk:"cloud" autogen:"omitjsonupdate"`
	Geography types.String `tfsdk:"geography" autogen:"omitjsonupdate"`
	ProjectId types.String `tfsdk:"project_id" apiname:"groupId" autogen:"omitjson"`
	Name      types.String `tfsdk:"name"`
	Secret    types.String `tfsdk:"secret" autogen:"sensitive,omitjson"`
}
