name: "Run Script and Commit Changes"
description: "Runs a specified script and commits changes to a file, with GPG signing."
author: "svc-apix-bot"

inputs:
  script_call:
    description: "The script to run."
    required: true
  file_to_commit:
    description: "The file to commit."
    required: true
  commit_message:
    description: "The commit message."
    required: true
  apix_bot_pat:
    description: "GitHub token for pushing commits."
    required: true
  remote:
    description: "Remote repository URL."
    required: true
  gpg_private_key:
    description: "GPG private key for commit signing."
    required: true
  passphrase:
    description: "Passphrase for the GPG key."
    required: true
  repo-path:
    description: "Path to the repository."
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0
        token: ${{ inputs.apix_bot_pat }}

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version-file: ${{ format('{0}go.mod', inputs.repo-path) }}
    - name: Run specified script
      shell: bash
      run: ${{ inputs.script_call }}

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit changes
      shell: bash
      run: |
        if [[ $(git status --porcelain) ]]; then
          git pull
          git config --local user.email svc-api-experience-integrations-escalation@mongodb.com
          git config --local user.name svc-apix-bot
          git remote set-url origin ${{ inputs.remote }}
          git add ${{ inputs.file_to_commit }}
          git commit -m "${{ inputs.commit_message }}"
          git push origin
        else
          echo "No changes to commit."
        fi
