name: Update PURLs list for dependabot prs

on:
  pull_request

permissions:
  pull-requests: write
  contents: write
  repository-projects: read
jobs:
  update-purls:
    name: Update PURLs
    if: github.actor == 'dependabot[bot]' || contains(github.head_ref, 'atlas-sdk-update')
    uses: ./.github/workflows/run-script-and-commit.yml
    with:
      script_call: 'make gen-purls'
      file_to_commit: 'compliance/purls.txt'
      commit_message: 'chore: update purls.txt'
    secrets:
      apix_bot_pat: ${{ secrets.APIX_BOT_PAT }}
      remote: https://svc-apix-bot:${{ secrets.APIX_BOT_PAT }}@github.com/${{ github.repository }}  
      gpg_private_key: ${{ secrets.APIX_BOT_GPG_PRIVATE_KEY }}
      passphrase: ${{ secrets.APIX_BOT_GPG_PASSPHRASE }}