name: Check migration guide

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  check:
    if: ${{ contains(github.event.pull_request.title, '!') }}  
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d
        id: changes
        with:
          filters: |
            guides:
                - 'docs/guides/**'
      - if: ${{ steps.changes.outputs.guides == 'false' }}
        run: echo "PR with breaking changes but no migration guide was created or updated" && exit 1
