name: Check changelog entry file

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]

jobs:
  check:
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e
        with:
          go-version-file: 'go.mod'
      - run: make check-changelog-entry-file
