name: Check migration guide

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  check:
    if: ${{ contains(github.event.pull_request.title, '!') }}  
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        id: changes
        with:
          filters: |
            guides:
                - 'docs/guides/**'
      - if: ${{ steps.changes.outputs.guides == 'false' }}
        run: echo "PR with breaking changes but no migration guide was created or updated" && exit 1
