name: 'Generate resource checks'

# Set of validations run on each pull request and merged commits to master.
on:
  push:
    branches:
      - master
    paths:
      - tools/codegen/**
      - internal/serviceapi/**
  pull_request:
    paths:
      - tools/codegen/**
      - internal/serviceapi/**
  workflow_dispatch:

jobs:
  generate-resource-check:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version-file: 'go.mod'
      - run: make tools generate-resource-code
      - name: Find mutations
        id: self_mutation
        run: |-
          git add .
          git diff --staged --patch --exit-code > resource.repo.patch || echo "self_mutation_happened=true" >> "${GITHUB_OUTPUT}"
      - name: Fail build on mutation
        if: steps.self_mutation.outputs.self_mutation_happened
        run: |-
          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
          cat resource.repo.patch
          exit 1
