name: Notify Docs team

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changes.outputs.files }}
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        id: changes
        with:
          filters: |
            files:
              - '.changelog/**'
              - 'docs/**'
        
  slack-notification:
    needs: check
    if: ${{ needs.check.outputs.files == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Needed by sticky-pull-request-comment
    steps:
      - uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_DOCS }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.repository.name }}: hey ${{ secrets.SLACK_DOCS_TAG }}, this is APIx bot, can you please review <${{ github.event.pull_request.html_url }}|PR ${{ github.event.pull_request.number }}>? thanks a lot!"
                  }
                }
              ]
            }
      - uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88
        with:
          header: pr-title-slack-doc
          append: true
          message: "APIx bot: a message has been sent to Docs Slack channel"
