name: Update Atlas Go SDK

# Checks if a new Atlas Go SDK version is available and creates a pull request adjusting version in codebase. Runs once per week and can be triggered manually.
on:
 schedule:
   - cron: "30 8 * * TUE" # Every Tuesday at 8:30 AM 
 workflow_dispatch:
  
jobs:
  update-sdk:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: 'go.mod'
      - name: Update files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make tools update-atlas-sdk
      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          token: ${{ secrets.APIX_BOT_PAT }}
          title: "chore: Updates Atlas Go SDK"
          commit-message: "build(deps): bump go.mongodb.org/atlas-sdk"
          delete-branch: true
          branch: atlas-sdk-update
          body: Automatic update for MongoDB Atlas Go Client SDK
